harvard-lil/perma

perma_web/fabfile.py, perma_web/mirroring/middleware.py, perma_web/mirroring/tasks.py, perma_web/mirroring/urls.py, perma_web/mirroring/utils.py, perma_web/mirroring/views.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/storage_backends.py, services/heroku/settings.py
More efficient mirroring logic when a new mirror connects.
=> Full database mirroring.

perma_web/perma/views/service.py
Here's the live change I made today, just so we can keep everything in sync until we figure out a permanent fix.
=> Disable thumbnail generation.

perma_web/perma/templates/user_management/created-links.html, perma_web/static/js/global.js, perma_web/static/js/links-list.js
- Fixes problem with GET requests in my apiRequest wrapper, so folder search works.
- Tweaks folder search to work more like current live version.
=> Folder search.

perma_web/perma/admin.py
Fix 500 error on admin console for registrars.
Fixes #800.
=> Fix registrar admin.

perma_web/perma/templates/single-link.html, perma_web/perma/views/common.py, perma_web/perma/views/user_management.py
- Show vest/darchive/delete buttons for staff (registry) users.
- Show darchive/delete buttons for non-vesting users.
Fixes #806.
=> Show single link page buttons.

perma_web/perma/settings/utils/post_processing.py
This was running once per minute, every other hour.
=> Fix cron job timing.

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/urls.py, perma_web/perma/views/service.py, perma_web/static/js/create.js
Here's a revised version of Matt's pull req. I added image size checks in thumbnail creation and also in capturing. It would be nice to allow partial captures, but for now simply refusing to take screenshots above 50 megapixels is better than crashing.
=> Thumbnails2

perma_web/perma/templates/docs/faq.html, perma_web/perma/templates/docs/getting-started.html, perma_web/perma/templates/docs/index.html, perma_web/perma/templates/docs/libraries.html, perma_web/perma/templates/docs/perma-archive.html, perma_web/perma/templates/docs/perma-dark-archive.html, perma_web/perma/templates/docs/perma-link-creation.html, perma_web/perma/templates/docs/perma-link-vesting.html, perma_web/perma/templates/docs/perma-user-roles.html, perma_web/perma/templates/landing.html, perma_web/static/css/style-responsive.scss
=> Patched in a fix for the ugly pill naviation on the user docs

perma_web/perma/templates/single-link.html, perma_web/perma/views/common.py, perma_web/perma/views/service.py, perma_web/static/js/create.js
- Allow logged-in users to view homepage.
- Fix dark archive logic.
=> Mirror debug.

perma_web/perma/templates/js_config.html
We were AJAXing http, as pulled from settings, from https. Using
the // now.
=> A little patch: in prod, we were getting a cross domain issue.

perma_web/perma/templates/link-vest-confirm.html, perma_web/perma/views/link_management.py, perma_web/static/js/link-vest-confirm.js
=> closes #767

perma_web/perma/templates/link-vest-confirm.html, perma_web/perma/views/link_management.py, perma_web/static/js/link-vest-confirm.js
Remember the last folder used for vesting and automatically select it.
=> closes #840

perma_web/perma/templates/single-link.html, perma_web/perma/views/link_management.py, perma_web/static/css/style-responsive.scss
Vest from orange banner if signed in with vesting privs
=> closes 718

perma_web/warc_server/pywb_config.py
Fixes the problem we ran into on stage ...
=> Explicitly call django.setup for Django 1.7 compat.

perma_web/api/resources.py
to show all folders when vesting a link
=> bump limit on folder API call

Vagrantfile, perma_web/functional_tests/tests.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/settings/deployments/settings_testing.py, services/heroku/Procfile, services/heroku/extra_requirements.txt, services/vagrant/provision.sh, services/vagrant/provision_mysql.sh
- New build of our vagrant box based on Ubuntu 14, includes imagemagick, updated Python packages.
- Temporarily disable integration tests that were giving me trouble.
- Some Heroku tweaks.
=> Freshen Vagrant.

perma_web/perma/settings/deployments/settings_common.py
=> Fix thumbnail background color.

perma_web/static/robots.txt
(This needs to be hooked up in the nginx conf as well.)
=> Add robots.txt.

perma_web/perma/models.py
Simple fix for the admin error Claire reported.
Closes #917.
=> Remove unnecessary assert.

perma_web/perma/settings/deployments/settings_common.py, perma_web/warc_server/app.py
=> Log pywb errors to Django log

perma_web/perma/models.py
Cleaned up some crufty logic associated with getting a user's associated orgs and related org resources. fixes #876
=> Related vesting org cleanup.

developer.md, perma_web/perma/settings/settings.example.py
=> A couple of tiny notes for developers

perma_web/perma/admin.py, perma_web/perma/tests/test_admin.py, perma_web/requirements.txt
=> Fix admin bug, and add tests.

perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/registration/sign-up-courts.html, perma_web/perma/templates/registration/sign-up-faculty.html, perma_web/perma/templates/registration/sign-up-journals.html, perma_web/perma/templates/registration/sign-up.html, perma_web/perma/templates/user_management/approve_pending_registrar.html, perma_web/perma/views/user_management.py
nice page for already approved registrar requests
viewport on base template
=> closes #970 and closes #959

perma_web/api/resources.py, perma_web/fabfile/deploy.py
Loading icons on single-link tabs should now detect when archive finishes.
=> Fix loading icons.

perma_web/perma/templates/landing.html, perma_web/perma/templates/libraries.html, perma_web/perma/templates/registration/sign-up-courts.html, perma_web/perma/templates/registration/sign-up-faculty.html, perma_web/perma/templates/registration/sign-up-journals.html, perma_web/perma/templates/registration/sign-up.html
* Cut a bunch of the text on each page
* Reordered the tabs
* Removed the nav label as unnecessary
=> Learn more / sign up process

perma_web/perma/templates/libraries.html, perma_web/perma/templates/registration/sign-up-faculty.html, perma_web/perma/templates/registration/sign-up-journals.html
Reflecting some additional suggestions from @kdulin and @cdemarco
=> Minor changes to text on learn more pages

perma_web/perma/models.py, perma_web/perma/tasks.py
This fixes a playback problem on stage with new captures that have a redirect (e.g. capturing msnbc.com and having it forward to www.msnbc.com).
=> Content type fix.

perma_web/fabfile/heroku.py, services/heroku/heroku_settings.py
Just a tweak so we don’t have so many settings.py files …
=> Rename heroku settings file.

perma_web/fabfile/dev.py
Here’s the fab task to create all of our new-format warc files once we deploy.
=> Fab task to export warcs.

perma_web/api/resources.py
API requests to the list-archives endpoint (e.g. /api/v1/folders/27/archives/) will now take a total of 2 SQL queries, regardless of the number of archives returned.
Previously they could take (worst case) up to six queries *per archive*. This should be faster.
=> Optimize link API queries.

perma_web/fabfile/dev.py, perma_web/perma/models.py
(Backporting this to develop.)
=> Fix export_warcs task.

perma_web/perma/templates/manage-layout.html, perma_web/perma/templates/registration/login.html, perma_web/perma/templates/user_management/manage_orgs.html, perma_web/perma/templates/user_management/manage_single_organization.html, perma_web/perma/templates/user_management/manage_single_registrar.html, perma_web/perma/templates/user_management/settings-organizations.html, perma_web/perma/templates/user_management/user_add_to_registrar_confirm.html, perma_web/perma/tests/test_permissions.py, perma_web/perma/views/user_management.py, perma_web/static/css/style-responsive.scss
Link orgs in manage users panel.
=> Org and registrar users can see and edit their own info

perma_web/perma/migrations/0020_auto_20150826_1659.py, perma_web/perma/models.py
This will improve memento query speed for, say, all captures of http://example.com/.
=> Add an index on CDXLine.urlkey

perma_web/perma/tasks.py, perma_web/requirements.txt
=> Improved SSL support for captures.

perma_web/perma/templates/user_management/manage_users.html
registry users can once again add regular users
=> fixes #1010

perma_web/perma/templates/single-link.html, perma_web/static/js/links-list.js
=> Check capture status before displayed favicon.

perma_web/perma/templates/docs/index.html, perma_web/perma/templates/landing.html
=> Fix links in home page to relevant user guide

perma_web/perma/tasks.py
=> Patched up broken stats collection

perma_web/perma/views/common.py
Remove our special handling for ssl on live view (now that live view is gone) so logged-in buttons show. 
Also simplified source_type a bit, so we just have image and warc_download and otherwise forward to the bare URL.
=> Force ssl for single link view.

.travis.yml
Heroku's pipeline will be taking care of this now.
=> Disable travis-ci deploys

perma_web/functional_tests/tests.py, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/views/common.py, perma_web/static/js/create.js
Implements the create->view archive functionality.
=> Dev.post vesting.1056

perma_web/api/resources.py, perma_web/perma/models.py, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/views/link_management.py, perma_web/static/js/create.js
=> Add individual user to affiliation select

perma_web/perma/templates/user_management/create-link.html, perma_web/static/css/style-responsive.scss, perma_web/static/js/global.js
Just a quick one.
Includes styles for 
- record remaining count
- create affiliation selector
- modal window position fix
Selector's content seems wonky. Can we double check it?
And god only knows what the new create flow with do to the CI tester.......
=> Dow styles options

perma_web/perma/templates/archive/confirm/base-archive-confirm.html, perma_web/perma/templates/archive/confirm/dark-archive-link.html, perma_web/perma/templates/archive/confirm/link-delete-confirm.html, perma_web/perma/templates/archive/single-link.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js
- some work on the private page
- fixed styles on record page
- spinner work
- button work
- fixed all the record action confirm pages
- still incomplete work on banners
=> Dow styles private

perma_web/perma/templates/archive/single-link.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss
Couple little things to finish up (!?) the banners at all widths.
=> Dow.banners

perma_web/perma/templates/user_management/create-link.html, perma_web/static/js/create.js
Cleaned up the create js a little.
Fixed an error -- we were not redirecting to the single record     page on successful upload.
=> Cleaned up the create page JS a bit

perma_web/functional_tests/tests.py, perma_web/perma/templates/api_key_embedded_form.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/contact.html, perma_web/perma/templates/docs/developer/index.html, perma_web/perma/templates/libraries.html, perma_web/perma/templates/password_change_embedded_form.html, perma_web/perma/templates/registration/logout.html, perma_web/perma/templates/registration/sign-up-courts.html, perma_web/perma/templates/registration/sign-up-faculty.html, perma_web/perma/templates/registration/sign-up-journals.html, perma_web/perma/templates/registration/sign-up.html, perma_web/perma/templates/settings-layout.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/manage_single_user.html, perma_web/perma/templates/user_management/settings-organizations-change-privacy.html, perma_web/perma/templates/user_management/settings-organizations.html, perma_web/perma/templates/user_management/settings-password.html, perma_web/perma/templates/user_management/settings-profile.html, perma_web/perma/templates/user_management/settings-tools.html, perma_web/perma/templates/user_management/user_reactivate_confirm.html, perma_web/perma/templates/user_management/user_remove_registrar_confirm.html, perma_web/perma/templates/user_management/user_remove_registry_confirm.html, perma_web/static/css/_fonts.scss, perma_web/static/css/_placeholders-global.scss, perma_web/static/css/_vars-global.scss, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss
Many cleanup changes, outlined in commits!
Add after `dow.tuesday` pleeeez.
=> Dow.cleanup

perma_web/perma/templates/user_management/create-link.html, perma_web/static/js/create.js
=> Keep the URL in the URL box on the create page if the user switches org

perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/created-links.html, perma_web/static/js/links-list.js
=> Include private and delete labels in list of links

perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/created-links.html, perma_web/static/css/style-responsive.scss
Private links in links list have new styles
=> Dow.private link

perma_web/perma/templates/archive/archive-error.html, perma_web/perma/templates/archive/dark-archive.html, perma_web/perma/templates/archive/deleted.html, perma_web/perma/templates/archive/single-link.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss
Here's my work on private record pages, and on error pages.
BIG NOTE: I wasn't able to view **any** record page as a non–signed in user without pulling a fat Django error. I don't think it's anything *I* did, but worth checking!
Or maybe adding to the tests......
=> Dow.records

perma_web/perma/templates/about.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/static/js/create.js
1. Relabel vesting orgs and vesting users to orgs and users in drop down in header
2. Removed crufty stats static image in the about page
3. Removed vest button from single record page
4. Made the spinner on the create button a little snappier
=> A grab bag of little fixes

perma_web/perma/templates/registration/check_email.html, perma_web/perma/templates/registration/not_active.html, perma_web/perma/templates/registration/password_reset_complete.html, perma_web/perma/templates/registration/password_reset_confirm.html, perma_web/perma/templates/registration/password_reset_done.html, perma_web/perma/templates/registration/set_password.html
Early morning fixes to some account activation/signup pages. Good morning!
=> little fixes for account activation

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/templates/archive/confirm/link-delete-confirm.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/landing.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/created-links.html, perma_web/perma/tests/test_permissions.py, perma_web/perma/urls.py, perma_web/perma/views/link_management.py, perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js
We were duplicating almost all of our links list code and functionality. Makes sense to jam the pages together.
fixes #820
=> Squashing create and list links pages

perma_web/perma/templates/user_management/create-link.html
=> Switch link on create page to point to docs

perma_web/functional_tests/tests.py, perma_web/perma/templates/user_management/create-link.html, perma_web/static/css/style-responsive.scss, perma_web/static/js/links-list.js
- Entire row is a drag target, except for `a` tags.
- Stop random text getting selected during drag.
Closes #1149
=> Improved drag'n'drop for links list.

perma_web/perma/templates/archive/iframe.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/created-links.html, perma_web/perma/templates/user_management/manage_registrars.html, perma_web/perma/templates/user_management/manage_single_organization.html, perma_web/perma/templates/user_management/manage_single_registrar.html, perma_web/perma/templates/user_management/manage_users.html, perma_web/perma/templates/user_management/settings-organizations-change-privacy.html, perma_web/perma/templates/user_management/settings-profile.html, perma_web/perma/templates/user_management/user_add_registrar.html, perma_web/perma/templates/user_management/user_add_to_organization_confirm.html, perma_web/perma/templates/user_management/user_add_vesting_org.html, perma_web/perma/templates/user_management/user_delete_confirm.html, perma_web/perma/templates/user_management/user_leave_confirm.html, perma_web/perma/templates/user_management/user_reactivate_confirm.html, perma_web/perma/templates/user_management/user_remove_registrar_confirm.html, perma_web/perma/templates/user_management/user_remove_registry_confirm.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss
Just a few little fixes after the heat of Wednesday; and adapting to the new Create/Manage page. (Good idea!)
=> Dev.post vesting

perma_web/perma/templates/archive/base-archive-responsive.html, perma_web/perma/templates/base-responsive.html
It's hard for me to test on native mobile, so maybe we can merge and see how it goes?
=> Hack to (maybe) fix an iOS9 viewport scaling bug

perma_web/perma/tasks.py
Just a little tweak to set Capture.content_type for favicon captures.
=> Record favicon mime type.

perma_web/static/js/links-list.js
=> Handle folder link row clicks on mobile.

perma_web/static/js/create.js
=> Re-enable URL field after failure.

perma_web/perma/templates/admin/base_site.html
=> Fix admin logout link.

perma_web/api/resources.py, perma_web/api/tests/test_link_resource.py, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/docs/developer/public.html
=> Don't show link org in single-link page or API.

perma_web/warc_server/pywb_config.py
=> Fix link not found page.

perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js, perma_web/static/js/global.js, perma_web/static/js/links-list.js
Fixes #1195
(See that bug for discussion.)
=> Clearer API error when logged out.

perma_web/static/js/links-list.js
This is the same fix as #1212, but ports the fix to develop so we can kick out it before dev.post-vesting.
=> Fix link edit JS.

perma_web/static/js/links-list.js
- Link title/note edits use a cleaner saving technique, avoiding risk of losing last few characters.
- When a link is moved, we just remove it from the current folder listing instead of fetching the list of remaining links from the server.
Fixes #1207
Fixes #1208
=> Link editing and moving.

perma_web/requirements.txt, perma_web/static/pywb/vidrw.js, perma_web/static/pywb/wb.js, perma_web/static/pywb/wombat.js, perma_web/warc_server/pywb_config.py
This ports the fixes we just deployed on `develop` over to `dev.post-vesting`
=> Improve playbacks.

perma_web/warc_server/pywb_config.py
=> Prevent redirect loops.

perma_web/perma/templates/user_management/manage_orgs.html, perma_web/perma/templates/user_management/manage_single_organization.html, perma_web/perma/views/user_management.py, perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js
=> privacy settings edit and disabled affiliation on link creation

perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js
=> gray out links remaining on creation for regular users

perma_web/static/js/links-list.js
=> Select parent folder after deleting child.

perma_web/perma/templates/user_management/organization_delete_confirm.html, perma_web/static/js/create.js
=> fix delete org template and create page js error

app.json, perma_web/functional_tests/tests.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/settings/deployments/settings_heroku.py
This should fix the timezone issue that was messing up the monthly link count on perma-stage -- I switched to a Heroku DB provider that has timezones configured.
=> Switch Heroku DB for stage.

perma_web/static/js/create.js
=> another create js bug fix

perma_web/static/js/create.js, perma_web/static/js/links-list.js
=> Fix link creation in IE9.

perma_web/perma/templates/archive/base-archive-responsive.html, perma_web/perma/templates/contact-thanks.html, perma_web/perma/templates/contingency_plan.html, perma_web/perma/templates/landing.html, perma_web/perma/templates/rate_limit.html, perma_web/perma/templates/read_only_mode.html, perma_web/perma/templates/registration/not_active.html, perma_web/perma/templates/tools.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/deactivated.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss, perma_web/static/img/websites-change-square.svg
=> second pass on fixing those busted template pages

perma_web/perma/templates/landing.html, perma_web/perma/templates/user_management/create-link.html, perma_web/static/js/links-list.js
=> remove map from landing, add host to links list

perma_web/perma/tasks.py, perma_web/perma/templates/stats.html, perma_web/perma/tests/test_tasks.py
- Fix margins on stats page template.
- Fix python error when running get_nightly_stats() for the first time.
- Add test case to run get_nightly_stats() and verify that a new Stat object is created.
=> Stat tweaks.

perma_web/perma/templates/docs/faq.html, perma_web/perma/templates/landing.html, perma_web/perma/urls.py, perma_web/perma/views/common.py
(This is Matt's work from #1286, I just cherrypicked the stats stuff for this release.)
=> Live stats in FAQ and landing page.

perma_web/perma/templates/landing.html
You know, the little infinity chiclet after the original link.
Also created archives for things that ended up being private. And, the fastco article that didn't archive very well.
=> Added links to perma archives in the landing page

perma_web/api/resources.py, perma_web/functional_tests/tests.py, perma_web/static/js/create.js, perma_web/static/js/links-list.js
fixes:
- no longer relying on selected_organization, purely on localStorage to select last selected folder
- bug on new folder creation
* create new folder
* select new folder
* refresh page
* newly created folder should be selected
=> Creating new folder

perma_web/requirements.txt
Upgrade pywb to 0.11.0.
Fixes #1216
=> Update pywb to latest release.

perma_web/perma/tasks.py, perma_web/perma/templates/archive/iframe.html
=> Fix capture error; better playback failed message.

perma_web/api/resources.py, perma_web/api/validations.py, perma_web/perma/templates/user_management/create-link.html
When I updated the API to accept just target folder rather than target org, I also applied the monthly link limit to all new links, not just non-org. Oops.
=> Fix links limit not to apply to org folders.

perma_web/api/tests/test_current_user_authorization.py, perma_web/api/tests/test_current_user_resource.py, perma_web/api/tests/test_folder_authorization.py, perma_web/api/tests/test_folder_resource.py, perma_web/api/tests/test_link_authorization.py, perma_web/api/tests/test_link_resource.py, perma_web/api/tests/test_link_validation.py, perma_web/api/tests/utils.py, perma_web/perma/migrations/0027_auto_20151221_1933.py, perma_web/perma/migrations/0028_auto_20151221_2145.py, perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_testing.py, perma_web/perma/templates/user_management/manage_users.html, perma_web/perma/tests/test_forms.py, perma_web/perma/tests/test_urls.py, perma_web/perma/tests/test_views_auth.py, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/common.py, perma_web/perma/views/user_management.py, perma_web/requirements.txt, perma_web/warc_server/pywb_config.py
Probably good to do at the same time as the big vesting refactor I just pulled in from Matt, since we'll want to test things out pretty well after both.
=> Update Django to 1.8.

perma_web/functional_tests/tests.py, perma_web/perma/models.py, perma_web/perma/templates/about.html, perma_web/perma/templates/docs/perma-link-creation.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/tests/test_permissions.py, perma_web/perma/urls.py, perma_web/perma/views/common.py, perma_web/perma/views/link_management.py, perma_web/static/css/style-responsive.scss, perma_web/static/js/create.js, perma_web/static/js/links-list.js
- fixes #1327 
- finishes #1317 
- fixes #1272
- fixes #1030
=> links page fixes

perma_web/perma/admin.py
(Issue arising from Django 1.8 upgrade.)
=> Fix user edit in admin.

perma_web/perma/templates/base-responsive.html
Just meta tag stuff. Twitter and Facebook.
=> Meta tags everywhere

perma_web/perma/templates/user_management/create-link.html, perma_web/static/js/create.js, perma_web/static/js/links-list.js
@phillipsm @jcushman don't know if "Please select a folder" is the right wording there?
=> add - making user choose a folder if none is set in their preferences

perma_web/static/css/style-responsive-archive.scss
=> fix - remove overflow hidden from body, fix header in position

perma_web/fabfile/deploy.py
This approach doesn’t depend on the current state of your local master or develop branches or your origin — just checks out upstream/master and merges in upstream/develop.
=> New tag_new_release task

perma_web/perma/templates/archive/iframe.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/single-link.js
capturing header height using js, sizing iframe and its wrappers using css
@jcushman: flexbox can't deal with something (like our header) being position:fixed. The only way that I could see to handle this situation, where a header is not only fixed in place but also dynamically sized, is through js on window size event (unfortunately).
However, we're no longer sizing the iframe through javascript! So that's sort of something, right?
=> fix - top margin

perma_web/fabfile/deploy.py, perma_web/perma/tasks.py, perma_web/perma/templates/archive/iframe.html, perma_web/perma/templates/archive/single-link.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/single-link.js
This helps with #1336.
Some of the examples still don’t capture well with PhantomJS — would be good to move to Firefox.
=> Improved scrolling during capture.

perma_web/perma/settings/deployments/settings_common.py
=> Fix path to local-datetime.js.

perma_web/perma/templates/archive/iframe.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/single-link.js
also a bunch of spacing changes
=> fix - showing links remaining

perma_web/api/resources.py, perma_web/api/urls.py, perma_web/static/js/create.js, perma_web/static/js/links-list.js
instead of having to reresh for the most up to date number
closes #1294
=> fix - showing links_remaining in real time

perma_web/perma/utils.py, perma_web/perma/views/user_management.py
Filter out user_deleted=True links for annotate() counts.
Fixes #1332
=> Better link counts

perma_web/perma/templates/stats.html, perma_web/static/css/_mixins-global.scss, perma_web/static/css/style-responsive.scss, perma_web/static/js/stats.js
A few tweaks to make stats look better on different devices.
=> Stats style

perma_web/perma/storage_backends.py
Transitional — if enabled on prod this will write a backup to S3 on every file save, without otherwise changing how we interact with the local filesystem.
=> Add S3-backup storage.

perma_web/fabfile/deploy.py
We can now turn on maintenance mode with `fab -Hperma deploy.maintenance_mode_on`.
maintenance_mode_on is also automatically called by the `deploy` task.
This required a change to the nginx conf, so if the `maintenance_on.html` file exists it goes into maintenance mode.
=> Maintenance mode fab tasks

perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/user_management/stats.html, perma_web/perma/tests/test_permissions.py, perma_web/perma/urls.py, perma_web/perma/views/user_management.py
First pass at a stats page for admin users — lives in the menu under “Site stats”
=> Admin stats page

perma_web/api/validations.py, perma_web/requirements.txt
Update PyPDF2 to fix error when validating nonconforming PDF.
Catch PyPDF2 errors during validation.
=> Better PDF upload handling.

.buildpacks, .travis.yml, perma_web/perma/tasks.py, services/vagrant/provision.sh
Once this is deployed, we can update the actual binary on production.
=> Upgrade Phantomjs to 2.1.1

perma_web/static/js/create.module.js, perma_web/static/js/folder-tree.module.js
=> My Links remaining countdown in odd places

perma_web/static/js/folder-tree.module.js, perma_web/static/js/links-list.module.js
=> Move links using drag and drop

perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/includes/upper_right_menu.html, perma_web/perma/views/common.py
=> Use include file for dropdown menu template.

perma_web/perma/templates/user_management/stats.html, perma_web/perma/urls.py, perma_web/perma/views/user_management.py
Chunks of the admin stats load individually over JSON, letting us include stuff that takes longer to load.
=> Admin stats load progressively.

perma_web/perma/tasks.py
=> fix - setting archive sponsor only if organization exists 

perma_web/perma/templates/user_management/stats.html, perma_web/perma/views/user_management.py, perma_web/static/vendors/handlebars/handlebars.js, services/celery/celery.conf
=> Add list of current celery jobs to admin stats

perma_web/perma/views/link_management.py
Also removed some unused imports.
=> Add perms check before showing user_delete_link form.

perma_web/perma/settings/deployments/settings_dev.py, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/create.module.js, perma_web/static/js/folder-tree.module.js, perma_web/static/js/links-list.module.js
finishes #1423 
+ added WARC_HOST to settings_dev since we're requiring it now
+ added more margin to show error message for error warc
=> Updating dropdown path on folder name edit

perma_web/perma/views/common.py
@jcushman does this look right to you?
It's live on perma-test: https://perma-test.law.harvard.edu/3KBJ-K2PV if you want to try it out
[Memento validator](http://mementoweb.org/tools/validator/info.html?uri=https%3A%2F%2Fperma-test.law.harvard.edu%2F3KBJ-K2PV&type=memento&datetime=Sun%2C+01+Apr+2010+12%3A00%3A00+GMT&aggregator=http%3A%2F%2Ftimetravel.mementoweb.org%2Ftimegate%2F&follow=on&Submit=Submit)
[Another memento](http://mementoweb.org/tools/validator/info.html?uri=https%3A%2F%2Fperma-test.law.harvard.edu%2Fwarc%2Fdp.la&type=memento&datetime=Sun%2C+01+Apr+2010+12%3A00%3A00+GMT&aggregator=http%3A%2F%2Ftimetravel.mementoweb.org%2Ftimegate%2F&follow=on&Submit=Submit)
=> fix - using correct header and header format

perma_web/perma/templates/api_key_embedded_form.html, perma_web/perma/views/user_management.py
Our regenerate api key had regressed. We had somehow inserted an extra form element. Fixes #1455
Also removed three crufty view functions that support old export
and batch logic
=> Fixes API key regeneration

.travis.yml, perma_web/functional_tests/tests.py, perma_web/perma/models.py, perma_web/perma/tasks.py, perma_web/perma/tests/test_permissions.py, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/tests/utils.py, perma_web/perma/views/user_management.py
Increases test coverage a bit, and makes future test coverage easier.
=> Refactor user management tests.

perma_web/requirements.txt, perma_web/static/pywb/scroll-webkit.css, perma_web/static/pywb/wb.js, perma_web/static/pywb/wombat.js, perma_web/warc_server/pywb_config.py
Also bump pywb to latest version (minor version upgrade).
=> Fix pywb error from missing not-found view

perma_web/static/js/create.module.js
=> fix - populating url field through bookmarklet

perma_web/perma/models.py
=> Check legacy GUIDs for zero vs. letter O confusion

perma_web/requirements.txt
=> Upgrade fabric

perma_web/perma/models.py
Hotfix — already applied on production.
=> Use indexed query.

perma_web/perma/tasks.py, perma_web/requirements.txt
before merging to production, make sure to run: 
```
mysql -e "select guid from perma_link where uploaded_to_internet_archive=True" -uperma -pperma perma > links_without_metadata.txt
```
=> Internet archive metadata fix

perma_web/perma/tasks.py
Shortens each capture by 1 to 2 seconds
=> Capture sleep speedups

install.md
A couple of little things I caught when walking through the install guide
=> Tiny install guide fixes

perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/user_management.py
- Also threw in some tests for the demote-user views
Fixes #1506
=> Handle case where user demotes themselves and then can't see the page

perma_web/perma/utils.py, perma_web/perma/views/user_management.py
=> Fix form data for org edit

perma_web/perma/forms.py, perma_web/perma/templates/user_management/user_add_confirm.html, perma_web/perma/templates/user_management/user_add_to_organization_confirm.html, perma_web/perma/templates/user_management/user_add_to_registrar_confirm.html, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/user_management.py
=> Better handling of org to registrar upgrades

perma_web/requirements.in, perma_web/requirements.txt, perma_web/static/pywb/wombat.js
Reverts harvard-lil/perma#1542
=> Revert "Upgrade pywb to 0.30.1"

perma_web/perma/admin.py, perma_web/perma/migrations/0007_auto_20160527_1625.py, perma_web/perma/migrations/0008_auto_20160531_1432.py, perma_web/perma/models.py, perma_web/perma/signals.py, perma_web/perma/templates/user_management/manage_orgs.html, perma_web/perma/templates/user_management/manage_registrars.html, perma_web/perma/templates/user_management/manage_users.html, perma_web/perma/tests/test_link_count_caching.py, perma_web/perma/utils.py, perma_web/perma/views/user_management.py
Merge in #1402 with some tweaks
=> Phillipsm develop.1402

perma_web/perma/models.py
=> Make max_length match initial migration

perma_web/api/resources.py, perma_web/fabfile/dev.py, perma_web/fixtures/users.json, perma_web/perma/admin.py, perma_web/perma/forms.py, perma_web/perma/migrations/0008_auto_20160602_1911.py, perma_web/perma/migrations/0009_auto_20160602_1937.py, perma_web/perma/models.py, perma_web/perma/tasks.py, perma_web/perma/templates/user_management/approve_pending_registrar.html, perma_web/perma/templates/user_management/manage_registrars.html, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/common.py, perma_web/perma/views/user_management.py
=> Add deny option for registrar request

perma_web/perma/templates/user_management/stats.html, perma_web/perma/views/user_management.py
=> Show average queue and capture time on admin stats

perma_web/fabfile/dev.py, perma_web/perma/migrations/0010_fix_weekstats.py, perma_web/perma/models.py
Please rerun fab dev.build_week_stats when we deploy
fixes #1548
=> Patched up weeklystats bug

perma_web/perma/templates/archive/single-link.html, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/helpers/dom.helpers.js, perma_web/static/js/single-link-with-permissions.module.js
=> Single link fixes

perma_web/static/js/single-link.module.js
=> fix - margin top gets updated on window resize now

perma_web/perma/settings/deployments/settings_common.py, perma_web/static/js/single-link-permissions.module.js, perma_web/static/js/single-link.module.js
- Avoid repeating single link logic for logged-out and logged-in users.
- Fix issue with single link header sizing — take border into account.
- Fix cancel button variable name.
=> Single link js tweaks

perma_web/perma/templates/archive/single-link.html
=> fix - delete button is now just an <a>

perma_web/static/js/single-link-permissions.module.js
fix - SingleLinkPermissionsModule doesn't have adjustTopMargin, it's been moved to SingleLinkModule
@jcushman should this be a hotfix?
cc: @phillipsm
=> errors on window resize

perma_web/perma/templates/archive/base-archive-responsive.html, perma_web/perma/templates/archive/single-link.html, perma_web/static/js/single-link.module.js
fix - any authenticated user getting single link with permissions module, as well as all necessary helpers
=> authenticated user can navigate from inside of single-link page

perma_web/api/resources.py, perma_web/api/tests/utils.py, perma_web/api/urls.py, perma_web/lockss/urls.py, perma_web/monitor/urls.py, perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/settings/deployments/settings_dev.py, perma_web/perma/settings/deployments/settings_prod.py, perma_web/perma/settings/deployments/settings_travis.py, perma_web/perma/templatetags/as_json.py, perma_web/perma/urls.py, perma_web/perma/utils.py, perma_web/perma/views/common.py, perma_web/perma/views/user_management.py, perma_web/requirements.in, perma_web/requirements.txt, perma_web/urls.py
Also upgrades tastypie and ratelimit to latest versions for compatibility.
=> Upgrade to Django 1.9

perma_web/api/resources.py
Only appending hash if a file is getting replaced
Fixes #1556
=> Appending hash to warc_url name in file replace

perma_web/fabfile/dev.py
=> fix - not starting a new internetarchive session on every link

perma_web/fabfile/dev.py
Useful to fix perma_cdxline if `surt` library changes how it canonicalizes urls.
=> Add regenerate_urlkeys task

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/views/common.py, perma_web/warc_server/pywb_config.py
Vary: Accept-Datetime header problems still remaining
partially finishes #1611
=> Memento header fix

perma_web/fabfile/deploy.py, perma_web/perma/celery.py, perma_web/perma/utils.py, perma_web/perma/wsgi.py, perma_web/warc_server/opbeat_wrapper.py, perma_web/warc_server/pywb_config.py
- Remove generic wsgi wrapper that caused mysql connection leak.
- Add performance monitoring for pywb and celery.
=> Opbeat updates.

perma_web/perma/storage_backends.py
Example config:
```
DEFAULT_FILE_STORAGE = 'perma.storage_backends.RedundantMediaStorage'
PRIMARY_FILE_STORAGE = 'perma.storage_backends.FileSystemMediaStorage'
SECONDARY_FILE_STORAGE = 'perma.storage_backends.FileSystemMediaStorage'
SECONDARY_MEDIA_ROOT = os.path.join(SERVICES_DIR, 'django/generated_assets_backup/')
```
=> Allow arbitrary redundant storage

perma_web/api/tests/test_link_resource.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py
… until we get to fixing #1640.
Stolen code from Jack. Fixed tests so we can merge.
=> Put a/v asset capture behind feature flag

perma_web/perma/tasks.py
Some captures were failing because content type was detected incorrectly.
This is because content type was being detected according to the first *response* to finish processing, which wasn’t necessarily the first request. Hence content type would be drawn from a random CSS file instead of the base HTML file.
This pull req makes sure that we examine responses by request order, instead of by the order they finished.
This was done as a hotfix because I couldn’t reproduce the problem locally …
=> Hotfix: improve content type detection for captures

perma_web/perma/templates/archive/single-link.html, perma_web/static/js/single-link.module.js
=> Dropdown fix

perma_web/api/tests/test_link_resource.py, perma_web/dev_requirements.txt, perma_web/fabfile/dev.py, perma_web/fixtures/archive.json, perma_web/perma/models.py, perma_web/perma/templates/archive/single-link.html, perma_web/perma/views/common.py
- Add tasks to check archive playbacks
- Automatically forward to screenshot view if screenshot worked and primary capture didn’t
=> Archive checks

perma_web/perma/settings/deployments/settings_common.py
=> Re-enable mysql init command

perma_web/perma/templates/archive/single-link.html
=> make private by policy message more explicit

perma_web/requirements.in, perma_web/requirements.txt
Also remove a few packages that have been there for a long time and are no longer used.
=> Update pip packages

perma_web/perma/templates/docs/index.html, perma_web/perma/templates/docs/perma-link-creation.html
Per #1279. Perhaps not the best writing, but tries to avoid interrupting the flow of the existing prose and distracting first-time users with too many options.
=> Add bookmarklet ref in user docs

perma_web/perma/templates/base-responsive.html
=> Twitter link

perma_web/perma/templates/docs/faq.html
Only claim support for IE 10+ per #1681. Also tweak a few things I noticed while the file was open.
=> FAQ tweaks

perma_web/perma/forms.py, perma_web/perma/templates/404.html, perma_web/perma/templates/500.html, perma_web/perma/templates/archive/dark-archive.html, perma_web/perma/templates/archive/deleted.html, perma_web/perma/templates/docs/developer/index.html, perma_web/perma/templates/docs/faq.html, perma_web/perma/templates/includes/fieldset.html, perma_web/perma/utils.py, perma_web/perma/views/common.py
Adds more details about a user to the email's footer; adds a user-tweakable subject line; passes in context-sensitive subject lines where possible when we link to contact form.
=> Spruce up contact email

perma_web/requirements.in, perma_web/requirements.txt
Updates internetarchive package to match current version of requests
=> Upgrade internetarchive

Vagrantfile
I noticed that VirtualBox was complaining about Vagrant trying to use too many CPUs. This reduces CPU count to 1/2 of physical cores. Unscientifically, tests ran faster after reducing CPU count.
=> Use fewer CPUs for virtualbox

perma_web/functional_tests/tests.py, perma_web/perma/templates/memento/query.html, perma_web/perma/tests/test_permissions.py, perma_web/perma/tests/test_views_error_management.py, perma_web/perma/tests/utils.py, perma_web/perma/views/error_management.py, perma_web/warc_server/pywb_config.py
- JS error details are captured for logged-out users.
- Integration tests make sure that js errors are recorded.
- Integration tests report any unexpected JS errors.
- More test coverage for JS error reporting views.
- Fix JS error uncovered by tests in pywb search result template.
=> JS error recording fixes

perma_web/perma/tasks.py
Fix a few issues I noticed on stage when testing the last pull
=> More capture tweaks

perma_web/fabfile/deploy.py
Add command `fab deploy.release_to_stage` to copy `develop` branch to `stage`.
Modify `fab deploy.tag_new_release` to suggest the next tag.
=> Add stage branch to deploy script.

perma_web/fabfile/dev.py, perma_web/perma/tasks.py
Remove sponsor field from Internet Archive uploads. There’s already a hotfix for this on prod.
=> Internet Archive sponsor

perma_web/api/resources.py, perma_web/api/validations.py, perma_web/functional_tests/tests.py, perma_web/perma/templates/archive/includes/upload_your_own.html, perma_web/static/js/create.module.js
=> Handle upload form submit when no file selected 

perma_web/perma/tests/test_views_user_management.py
Tests describe current behavior of the form. Possibly worth readdressing. #1749 #1746
=> Tests for court sign up form

perma_web/perma/tests/test_views_user_management.py
Tests describe current behavior of the form. Possibly worth readdressing. #1749
=> Tests for journal signup form

perma_web/perma/tests/test_views_user_management.py
Tests describe current behavior of the form. Possibly worth readdressing. #1749
=> Tests for faculty signup form

perma_web/perma/tasks.py
Fixes capture failure recently reported by user
=> Catch urlerror in capture task

perma_web/fixtures/folders.json, perma_web/fixtures/users.json, perma_web/perma/templates/user_management/manage_users.html, perma_web/perma/tests/test_views_user_management.py
Might need a quick rebase if merged after #1758
=> Tests for the filters on manage views that list users/orgs/registrars

perma_web/perma/templates/archive/includes/upload_your_own.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/views/common.py
=> Show MAX_ARCHIVE_FILE_SIZE on all the upload forms

perma_web/fabfile/dev.py
… fab task kept for example purposes.
=> Add check_s3_hashes task

perma_web/perma/models.py
=> Use default_storage instead of os.rename

perma_web/functional_tests/tests.py, perma_web/perma/tests/test_views_link_management.py, perma_web/perma/views/link_management.py, perma_web/requirements.in, perma_web/requirements.txt
Might add more for the templates later.
=> Some tests for the link management view

perma_web/perma/tests/test_views_user_management.py
(to catch that one line of red)
=> Password creation form loads

perma_web/perma/tasks.py
=> Upload to IA from local temp file

perma_web/functional_tests/tests.py, perma_web/perma/templates/user_management/manage_users.html, perma_web/static/bundles/global-styles.css, perma_web/static/css/style-responsive.scss
CSS tweaks. Functional tests hit most perma routes.
=> More node transition tweaks

perma_web/perma/templates/user_management/create-link.html, perma_web/static/bundles/create.js, perma_web/static/bundles/single-link-styles.css, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/folder-tree.module.js
- https://github.com/harvard-lil/perma/issues/1806
- https://github.com/harvard-lil/perma/issues/1805
- https://hlslil.slack.com/archives/perma/p1479222984000059
- https://hlslil.slack.com/files/brett_j/F323HB21W/screen_shot_2016-11-15_at_10.11.15_am.png
=> Fix blocker + css issues on stage

perma_web/static/bundles/global-styles.css, perma_web/static/css/style-responsive.scss
Fixes https://github.com/harvard-lil/perma/issues/1422
=> MINOR: tweak folder list input css.

perma_web/functional_tests/tests.py
=> add functional test for viewing a capture while logged out

perma_web/api/tests/test_link_resource.py, perma_web/api/tests/utils.py, perma_web/perma/tasks.py
=> support x-robots-tag header

perma_web/perma/views/common.py, perma_web/perma/views/user_management.py
render templates using render, not render_to_response
=> Prep for Django 1.10, part 1

perma_web/perma/templates/about.html, perma_web/perma/templates/archive/base-archive-responsive.html, perma_web/perma/templates/archive/iframe.html, perma_web/perma/templates/archive/includes/upload_your_own.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/templates/base-responsive.html, perma_web/perma/templates/contact.html, perma_web/perma/templates/docs/developer/toc.html, perma_web/perma/templates/docs/index.html, perma_web/perma/templates/docs/libraries.html, perma_web/perma/templates/docs/organizations.html, perma_web/perma/templates/docs/perma-link-creation.html, perma_web/perma/templates/landing.html, perma_web/perma/templates/layout-responsive.html, perma_web/perma/templates/privacy_policy.html, perma_web/perma/templates/registration/password_reset_form.html, perma_web/perma/templates/registration/sign-up-libraries.html, perma_web/perma/templates/search.html, perma_web/perma/templates/terms_of_service.html, perma_web/perma/templates/user_management/create-link.html, perma_web/perma/templates/user_management/user_remove_registrar_confirm.html, perma_web/static/bundles/create.js, perma_web/static/bundles/global-styles.css, perma_web/static/bundles/single-link-styles.css, perma_web/static/css/style-responsive-archive.scss, perma_web/static/css/style-responsive.scss, perma_web/static/js/folder-tree.module.js, perma_web/static/js/links-list.module.js
This fixes all the invalid html I could find, but I didn't find a comprehensive way to check. Might have missed content written/altered via javascript; might not have checked every page.
=> Fix invalid html

perma_web/static/bundles/create.js, perma_web/static/js/links-list.module.js
Fixes https://github.com/harvard-lil/perma/issues/1847
=> FIX: infinite scroll

perma_web/static/bundles/create.js, perma_web/static/js/create.module.js
- Disabling both buttons on upload
- Showing spinner
- Removing spinner and enabling buttons on error 
finishes #1372
=> Upload your own

perma_web/perma/templates/email/registrar_user_ping.txt
spacing between sections added, and made shorter overall.
=> Final email text update

perma_web/perma/templates/email/registrar_user_ping.txt
final tweak before sending out. added asterisks to each section to help delineate sections.
=> Text spacing tweak

perma_web/perma/models.py, perma_web/perma/tasks.py, perma_web/perma/templates/user_management/stats.html, perma_web/perma/views/user_management.py
Addresses https://github.com/harvard-lil/perma/issues/1888
See comments in tasks.py for full discussion of the problem.
Review of my while loop and repeat_until_truthy very welcome!!!
=> Address failure in retrieval of meta tags

perma_web/perma/tasks.py
=> FIX: Don’t raise if timeout.

perma_web/perma/templates/email/registrar_contact.txt, perma_web/perma/views/common.py
removed user's name, adding {{user email}} and also needing a list of user orgs.
=> tweaking wording, introducing new variable

perma_web/perma/templates/email/admin/contact.txt, perma_web/perma/templates/email/registrar_contact.txt
prior to sending support requests to registrars.
=> MINOR: tweak “troubleshooting” footer message

perma_web/perma/templates/user_management/create-link.html, perma_web/static/bundles/create.js, perma_web/static/bundles/global-styles.css, perma_web/static/bundles/search.js, perma_web/static/bundles/single-link-permissions.js, perma_web/static/css/style-responsive.scss, perma_web/static/js/helpers/link.helpers.js
=> Show failed captures on manage/create page

perma_web/perma/templates/docs/developer/index.html
adding a note about creating an archive using our API inside a specific folder.
=> add - creating archive in folder

perma_web/fabfile/dev.py, perma_web/fixtures/mirrors.json, perma_web/lockss/tests/test_views.py, perma_web/lockss/views.py, perma_web/perma/tests/utils.py
=> Test LOCKSS views

perma_web/perma/email.py, perma_web/perma/models.py, perma_web/perma/tests/test_models.py, perma_web/perma/utils.py
There must be a better way....
=> Make datetimes TZ-aware to suppress test warnings

perma_web/perma/views/service.py
fixes #1981 - a timezone bug in the js stats graphs
=> fixes a timezone bug in the js stats graphs

perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py
See https://github.com/harvard-lil/perma/pull/1999. This is a new version.
=> first pass at refactoring proxied_capture

.gitignore, perma_web/perma/settings/deployments/settings_common.py, perma_web/setup.cfg
Just a couple of quick tweaks from my experiment a few weeks ago with pytest.
=> Pytest tweaks

perma_web/perma/tasks.py
Ben's great catch!! This should explain at least some number of the captures that are stuck permanently in "pending" state.
=> Dont swallow timeout

perma_web/perma/templates/user_management/organization_delete_confirm.html
see https://github.com/harvard-lil/perma/issues/1998
=> FIX: cancel button should point manage/organizations

perma_web/requirements.in, perma_web/requirements.txt
=> Django 1.10

perma_web/perma/templates/403_csrf.html
Per https://github.com/harvard-lil/perma/issues/1952
=> NEW: add template for CSRF failure

perma_web/perma/tasks.py
I missed a couple spots in https://github.com/harvard-lil/perma/pull/2030
This also removes the attempt to update page metadata each time we load an iframe, as it sometimes throws an out-of-bounds index exception, which causes the entire media url retrieval function to fail. Since I was the one pressuring people into checking page metadata more than once, and I don't miss this line, I'm guessing nobody will miss it... If I'm wrong, just holler, and I'll spend more time figuring out why/when the index error is thrown instead.
=> Working on #2021, part 2

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/views/error_management.py
=> Fix images on custom CSRF failure page

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py
Suppress verbose logging via config rather than by disabling the logger in tasks.py
=> Suppress verbose logging via config

perma_web/warc_server/pywb_config.py
Suppresses lines like this unless in debug mode
2017-05-30 19:02:21,814 [INFO] thread 140630086086160 pywb_config.py 446: Got content from local disk
=> Trivial: lower a log statement level

perma_web/warc_server/pywb_config.py
=> Improve pywb database connection closing

perma_web/perma/tasks.py
=> update - passing over metadata files when deleting

perma_web/perma/settings/deployments/settings_testing.py, perma_web/perma/tests/test_views_user_management.py
- fixes indentation on tests
- removes stray "court" references
- updates subject line on firm account request email
=> Minor fixes for firm signup views

perma_web/perma/templates/user_management/manage_users.html
=> fix - filter Upgrade interest by firm

perma_web/perma/templates/email/admin/registrar_request.txt, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/user_management.py
=> Registrar requested by

perma_web/api/serializers.py, perma_web/perma/models.py, perma_web/perma/tasks.py, perma_web/perma/utils.py, perma_web/perma/views/common.py, perma_web/warc_server/pywb_config.py
While investigating those persistent periodic RDS errors we're getting, read through a lot of the memento-related code. I didn't find anything implicated in the RDS errors, but did a little drive-by refactoring while reading through.
=> Minor refactoring

perma_web/perma/models.py, perma_web/perma/views/user_management.py
to prevent potential interference from imported modules, who may set random.seed()
=> Use system random instead of globally seeded random

perma_web/perma/models.py, perma_web/perma/tasks.py, perma_web/perma/utils.py
and a few tiny wording tweaks.
No, this shouldn't be one giant commit. Yes, it's one giant commit.
=> Only write to default_storage once; warc writing code in utils.py

perma_web/perma/utils.py, perma_web/perma/views/user_management.py
If this works, we should deploy reasonably soon, to fix broken library signup form.
=> More reasonable error handling.

perma_web/fixtures/archive.json, perma_web/perma/models.py, perma_web/perma/templates/archive/iframe.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/views/common.py
Admit failure in cases like this:
=> Don't expose failed capture jobs

perma_web/fabfile/dev.py, perma_web/perma/email.py, perma_web/perma/templates/email/special.txt
The inelegance of this doesn't really bother me. If it bothers you, I'll take a second pass ;-)
=> Lazy approach to sending a one-time email.

perma_web/functional_tests/tests.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/templates/archive/includes/upload_your_own.html, perma_web/perma/templates/archive/single-link.html, perma_web/perma/tests/test_views_common.py, perma_web/perma/urls.py, perma_web/perma/views/common.py, perma_web/static/bundles/create.js, perma_web/static/bundles/single-link-permissions.js, perma_web/static/js/create-link.module.js, perma_web/static/js/single-link-permissions.module.js
https://github.com/harvard-lil/perma/issues/2155
=> Replace references to Linky in codebase

perma_web/perma/templates/api_key_embedded_form.html, perma_web/perma/templates/password_change_embedded_form.html, perma_web/perma/views/user_management.py
https://github.com/harvard-lil/perma/issues/2113
=> Remove unused context variable

.travis.yml, install.md, perma_web/api/tests/utils.py, perma_web/fabfile/dev.py, perma_web/fixtures/sites.json, perma_web/functional_tests/tests.py, perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_dev.py, perma_web/perma/settings/settings.example.py, perma_web/perma/tests/test_views_error_management.py, perma_web/spec/javascripts/link.helpers.spec.js, services/nginx/nginx.conf
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
=> Serve at perma.test instead of .dev because Google ruined everything

perma_web/requirements.txt
See https://docs.djangoproject.com/en/2.0/releases/1.11.9/
=> Upgrade Django to 1.11.9

perma_web/perma/settings/utils/post_processing.py, perma_web/perma/tasks.py, perma_web/perma/templates/email/admin/js_errors.txt, perma_web/perma/tests/test_tasks.py
=> add - sending email digest of last week's uncaught JS errors to perma admins

perma_web/perma/settings/deployments/settings_prod.py
Forgot to add the new job name into the JOB_NAMES list
=> fix - why not turn the celery job on while we're at it

perma_web/perma/templates/docs/developer/toc.html
(I forgot to do this in https://github.com/harvard-lil/perma/pull/2224)
=> Fix dev docs TOC

perma_web/perma/templates/user_management/manage_orgs.html, perma_web/perma/templates/user_management/manage_registrars.html, perma_web/perma/templates/user_management/manage_users.html, perma_web/static/bundles/global-styles.css, perma_web/static/css/style-responsive.scss
Fixes https://github.com/harvard-lil/perma/issues/1323
=> CSS tweaks

perma_web/perma/templates/docs/perma-link-creation.html, perma_web/static/bundles/global-styles.css, perma_web/static/css/style-responsive.scss
Addresses https://github.com/harvard-lil/perma/issues/1932
=> Tweak example citation: add caption, add accessible text.

perma_web/perma/views/user_management.py
Fixes https://github.com/harvard-lil/perma/issues/1886
=> Appropriately classify users associated with deleted orgs.

perma_web/perma/models.py, perma_web/perma/settings/utils/post_processing.py, perma_web/perma/tasks.py, perma_web/perma/templates/email/admin/js_errors.txt, perma_web/perma/tests/test_tasks.py, perma_web/static/js/error-handler.js
- gave cron job a minute value so it doesn't run 60 times an hour
- formatted errors for emails, sending only very last value for error stack (added sending error id for easier tracking down of errors)
=> UncaughtJS errors

perma_web/warc_server/pywb_config.py
=> fix - better/prettier date formatting

docker-compose.yml, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/templates/registration/password_update_form.html, perma_web/perma/tests/test_views_auth.py, perma_web/perma/urls.py, perma_web/perma/views/user_management.py, perma_web/requirements.txt
Applies recent Django security patch; reverts some of the logic introduced in https://github.com/harvard-lil/perma/commit/e983798f7225646726d6991f44fca5cf45337d97.
Devs should run pip-sync in their Vagrant box; Docker will build an updated image on next `docker-compose up`
=> Django 1.11.10 and associated fix

perma_web/perma/templates/email/new_user_added_by_other.txt, perma_web/perma/templates/email/new_user_added_to_org_by_other.txt, perma_web/perma/templates/email/new_user_added_to_registrar_by_other.txt, perma_web/perma/views/user_management.py
Addresses https://github.com/harvard-lil/perma/issues/1685
=> More informative emails when new users are created by existing users.

perma_web/perma/templates/base-responsive.html
Fixes https://github.com/harvard-lil/perma/issues/2245.
=> Accessibile logo

perma_web/perma/templates/admin/base_site.html, perma_web/perma/templates/docs/developer/index.html, perma_web/perma/templates/docs/index.html, perma_web/perma/templates/docs/libraries.html, perma_web/perma/templates/docs/perma-link-creation.html, perma_web/perma/templates/landing.html, perma_web/perma/templates/user_management/settings-tools.html
Addresses:
https://github.com/harvard-lil/perma/issues/2250
https://github.com/harvard-lil/perma/issues/2244
https://github.com/harvard-lil/perma/issues/2243
I'd be grateful for a proofreader's eye.
=> Provide descriptive alt text for images or mark aria-hidden.

perma_web/warc_server/pywb_config.py
Fixes https://github.com/harvard-lil/perma/issues/2280
=> Don't explode if archives request malformed urls during playback

perma_web/perma/templates/base-responsive.html
Addresses https://github.com/harvard-lil/perma/issues/2239
=> Try meta currently recommended by html5-boilerplate and bootstrap

perma_web/static/bundles/admin-stats.js, perma_web/static/bundles/create.js, perma_web/static/bundles/global-styles.css, perma_web/static/bundles/search.js, perma_web/static/bundles/single-link-permissions.js, perma_web/static/css/_mixins-global.scss, perma_web/static/css/style-responsive.scss, perma_web/static/js/folder-tree.module.js, perma_web/static/js/helpers/dom.helpers.js, perma_web/static/js/links-list.module.js
This is a first pass at https://github.com/harvard-lil/perma/issues/1218.
The styles look good on my browsers, but zoom settings are interfering somewhat with testing: I _think_ it's legitimately fine (at any standard zoom), but am not positive.
Scroll bars should appear when the content is too long, and not appear when the content fits. Folders and Links scroll separately. The Folders section heading with its important button, does not scroll. A subtle shadow should keep the Links list from looking peculiar during scrolling. Scroll bars should not bump other content out of the way. The Folders list should be horizontally scrollable, but the horizontal scroll bar should not appear. 
No scrolling:
Scrollable links, at the top:
Scrolling through links:
Scrolling folders and links at the …
=> Infinite scroll and footer access

perma_web/static/bundles/global-styles.css, perma_web/static/css/style-responsive.scss
Let's see how this looks.....
Still no sticky header for the link list, but maybe we'll like it......
=> Attempt better mobile styling for scrolling lists.

perma_web/requirements.txt
Pending further discussion/investigation....
=> Revert sorl-thumbnail for now

perma_web/requirements.txt
https://docs.djangoproject.com/en/2.0/releases/1.11.12/
=> Upgrade Django to 1.11.12

perma_web/warc_server/pywb_config.py
Note: this isn't a full patch of the Cookie module.
Our only interest here is to see if Perma's special cookie that grants access to a private link is set. We only need to be able to create a cookie object and check for our key. This patches the module sufficiently to let us do that. It does NOT attempt to patch the module such that it can fully handle cookies with colons as keys (parsing, etc.), because that involves too much code, and we wouldn't use any of it. For a more complete patch, see http://pythonfiddle.com/cookie-accepting-a-colon-as-a-key/ (although I note that fiddle leaves `_Translator` untouched.)
=> Don't explode if cookies with colons have been set during playback

perma_web/perma/models.py
Re-closes https://github.com/harvard-lil/perma/issues/1976
=> Add error handling per observed difficulties.

perma_web/perma/utils.py
closes https://github.com/harvard-lil/perma/issues/2181
=> If we are missing user agent or capture mime type, proceed as normal.

perma_web/perma/views/service.py
Closes https://github.com/harvard-lil/perma/issues/2069 and https://github.com/harvard-lil/perma/issues/1801
=> don't implicitly cast to ascii

perma_web/requirements.txt
See https://docs.djangoproject.com/en/2.0/releases/1.11.13/
=> Upgrade Django to 1.11.13

perma_web/perma/templates/archive/includes/link_batch_modal.html, perma_web/static/bundles/create.js, perma_web/static/js/link-batch.module.js
"Create A Link Batch" or "Link Batch Details", depending.
=> Tweak modal title.

perma_web/perma/settings/deployments/settings_prod.py, perma_web/perma/settings/utils/post_processing.py
=> Run run_next_capture every minute with celerybeat

perma_web/static/bundles/create.js, perma_web/static/bundles/global.css, perma_web/static/bundles/search.js, perma_web/static/bundles/single-link-permissions.js, perma_web/static/css/style-responsive.scss, perma_web/static/js/hbs/link.handlebars, perma_web/static/js/helpers/link.helpers.js
closes https://github.com/harvard-lil/perma/issues/2366
=> When captures are in progress, say so in the Link List

perma_web/static/bundles/create.js, perma_web/static/js/create-link.module.js, perma_web/static/js/link-batch.module.js
closes https://github.com/harvard-lil/perma/issues/2369
=> Hide "create many" link when a single PermaLink is in progress.

perma_web/perma/templates/docs/developer/toc.html
=> Remove "thing" from navigation.

perma_web/api/urls.py, perma_web/api/views.py, perma_web/npm-shrinkwrap.json, perma_web/package.json, perma_web/perma/templates/archive/includes/link_batch_modal.html, perma_web/static/bundles/create.js, perma_web/static/bundles/global.css, perma_web/static/bundles/global.js, perma_web/static/bundles/map.js, perma_web/static/bundles/search.js, perma_web/static/bundles/single-link-permissions.js, perma_web/static/bundles/single-link.js, perma_web/static/bundles/stats.js, perma_web/static/css/style-responsive.scss, perma_web/static/js/link-batch.module.js
closes https://github.com/harvard-lil/perma/issues/2362
=> CSV export handled server-side

perma_web/api/serializers.py, perma_web/perma/templates/archive/single-link.html
Closes https://github.com/harvard-lil/perma/issues/2327
=> Download links

perma_web/warc_server/pywb_config.py
I'm not sure about this. Workaround appears successful locally, but this is a symptom of a larger disconnect: if pywb wants latin-1, but websites supply utf-8, what are we supposed to do?
I think we should probably merge this workaround, and more fully investigate how modern pywb/WR handle encoding.
=> Ugly workaround for #2416

perma_web/api/tests/test_link_validation.py, perma_web/api/tests/utils.py, perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py
rather than 10s for headers during the validation process and 45s during the capture process
=> wait as long during validation as during capture

perma_web/perma/settings/deployments/settings_common.py, perma_web/warc_server/pywb_config.py
Override REFUSE_PLAYBACK in settings.py, so that we don't publicly expose blacklisted urls.
=> Mechanism for blocking the playback of arbitrary urls.

perma_web/perma/templates/email/registrar_user_ping.txt
updated registrar ping email for bulk link creation announcement, August 2018
=> updated registrar ping email for bulk link creation

perma_web/warc_server/pywb_config.py
Closes https://github.com/harvard-lil/perma/issues/2444 and https://github.com/harvard-lil/perma/issues/2442.
=> Timemap fixes

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/views/link_management.py
Closes https://github.com/harvard-lil/perma/issues/2438
=> Fallback count of celery workers

perma_web/perma/admin.py
Whoops! Meant to include this in https://github.com/harvard-lil/perma/pull/2455
=> Add link taglist to CaptureJob admin.

perma_web/perma/admin.py
Closes https://github.com/harvard-lil/perma/issues/2425
=> Display capture job count in link batch admin

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock, perma_web/api/tests/test_current_user_authorization.py, perma_web/api/tests/test_current_user_resource.py, perma_web/api/tests/test_folder_authorization.py, perma_web/api/tests/test_folder_resource.py, perma_web/api/tests/test_link_authorization.py, perma_web/api/tests/test_link_resource.py, perma_web/api/tests/test_link_validation.py, perma_web/api/tests/utils.py, perma_web/conftest.py, perma_web/fabfile/dev.py, perma_web/lockss/tests/test_views.py, perma_web/perma/tests/test_capture_job.py, perma_web/perma/tests/test_cloudflare_cache.py, perma_web/perma/tests/test_link_count_caching.py, perma_web/perma/tests/test_utils.py, perma_web/perma/tests/test_views_common.py, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/tests/utils.py
This PR makes a few changes to the way we run our tests, without actually changing any of our tests. I THINK it includes meaningful changes; a couple more commits experiments that didn't seem fruitful are available here: https://github.com/rebeccacremona/perma/commits/faster-tests.
There is still plenty of room for refactoring. Another day! Hopefully another day soon.
=> Faster tests

perma_web/perma/templates/email/admin/premium_request.txt, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/views/user_management.py
whoops. forgot to open a ticket in previous two PRs.
=> Like new firm/library, send email when new premium account requested

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock, perma_web/api/serializers.py, perma_web/api/tests/utils.py, perma_web/api/views.py, perma_web/fabfile/__init__.py, perma_web/fabfile/heroku.py, perma_web/lockss/admin.py, perma_web/lockss/views.py, perma_web/perma/admin.py, perma_web/perma/email.py, perma_web/perma/migrations/0006_add_internetarchive_status.py, perma_web/perma/settings/deployments/settings_heroku.py, perma_web/perma/settings/deployments/settings_prod.py, perma_web/perma/tasks.py, perma_web/perma/templatetags/carousel.py, perma_web/perma/tests/test_capture_job.py, perma_web/perma/tests/test_link_count_caching.py, perma_web/perma/tests/test_models.py, perma_web/perma/tests/test_permissions.py, perma_web/perma/tests/test_utils.py, perma_web/perma/tests/test_views_error_management.py, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/utils.py, perma_web/perma/views/user_management.py, perma_web/setup.cfg, perma_web/warc_server/pywb_config.py
This PR aims to upgrade and unpin all the packages I can without rocking the boat. That is: I don't want to mess with anything that might subtly break, or might affect capture (Werkzeug, requests, selenium, etc.)
We should kick this around a little on stage. If it doesn't work out of the box, most likely https://github.com/harvard-lil/perma/issues/2473 is implicated.
=> Upgrade minor packages

perma_web/perma/tasks.py
Not sure about this: making a PR to facilitate discussion. Would close https://github.com/harvard-lil/perma/issues/2477 and the underlying issue, https://github.com/harvard-lil/perma/issues/2019.
But I think this technique is pretty ridiculous.
TBD....
=> Patch warcprox's proxy function to be stoppable.

perma_web/perma/models.py
Should prevent https://github.com/harvard-lil/perma/issues/2491
=> Only create 1000 cdxlines at a time.

perma_web/perma/templates/docs/perma-link-creation.html
Updating b/c no-archive tag being ignored now
=> updates to private link docs

docker-compose.yml, perma_web/Dockerfile, perma_web/Pipfile, perma_web/Pipfile.lock
=> Update Django to latest; pin pip for pipenv bug.

perma_web/perma/tasks.py
Closes https://github.com/harvard-lil/perma/issues/2453
=> Don't die if server omits content-type.

docker-compose.yml, perma_web/.dockerignore, perma_web/Dockerfile
What version of pip and pipenv do our minions use? Do they update to latest on every deploy?
=> Unpin pip since https://github.com/pypa/pipenv/issues/2924 resolved.

perma_web/perma/templates/email/special.txt
To send ~11:45am on Weds morning, if convenient, via `fab dev.ping_registrar_users:email="special"`
=> Special email

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock, perma_web/api/middleware.py, perma_web/api/serializers.py, perma_web/api/tests/test_folder_authorization.py, perma_web/api/views.py, perma_web/fabfile/dev.py, perma_web/functional_tests/tests.py, perma_web/lockss/urls.py, perma_web/perma/admin.py, perma_web/perma/admin_utils.py, perma_web/perma/middleware.py, perma_web/perma/migrations/0001_initial.py, perma_web/perma/migrations/0003_capturejob.py, perma_web/perma/migrations/0009_auto_20160602_1937.py, perma_web/perma/models.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/tasks.py, perma_web/perma/tests/test_capture_job.py, perma_web/perma/tests/test_tasks.py, perma_web/perma/urls.py, perma_web/perma/utils.py, perma_web/perma/views/common.py, perma_web/perma/views/error_management.py, perma_web/perma/views/user_management.py, perma_web/urls.py
This PR attempts to resolve all the deprecation (and other) warnings captured by pytest during test runs.
One pywb warning (can't fix) and one MySQL warning (which I can't figure out) remain.
Once we have confidence this doesn't break everything, I'll upgrade us to Django 2.
=> Prep for Django 2

perma_web/perma/models.py, perma_web/perma/tests/test_models.py
squash these on merging for pride's sake, methinks
=> Fix non-deterministic test

README.md
I saw the top header in the README file wasn't rendering properly, and it was bugging me.
=> fix top-level header in README

perma_web/fabfile/dev.py, perma_web/perma/templates/email/new_user.txt, perma_web/perma/templates/email/new_user_added_by_other.txt, perma_web/perma/templates/email/special.txt
This will be deployed as a hotfix.
How it works: 
- run `fab dev.ping_all_users`, optionally supplying a list of one or more users to test with, optionally supplying a special list of users to exclude, optionally specifying a batch size (default = 500).
- Django emails up to `batch_size` users the text specified in `special.txt`, recording each user's ID in a tmp file. The tmp file is stored between runs: no matter how many times you run the function, Django won't email the same user twice.
- watch the Django log.info for updates
- watch the tqdm progress bar for progress, if tqdm works in the environment
- if you like what you see, respond to the prompt with "y" to run another batch of the same size, or "n"/any other character to stop. Resume by running again.
Here is a sample terminal …
=> Add an interruptible task to ping all users, in batches.

.gitignore, developer.md, docker-compose.yml, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/settings/deployments/settings_dev.py, perma_web/perma/settings/deployments/settings_testing.py, perma_web/perma/settings/settings.example.py, services/docker/perma-payments/settings.py.example
Much easier than what I've been doing!!
There's still some work to do to make Perma Payments more useful locally (it's hard to simulate responses from CyberSource), but, now that it is so much easier to run both Perma and Perma Payments at the same time locally, I'm a lot more motivated to do it LOL.
=> Perma Payments via from Docker Hub

docker-compose.yml, perma_web/perma/models.py, perma_web/perma/views/user_management.py
1) Didn't catch this when merging https://github.com/harvard-lil/perma/pull/2520
2) Two errors in resolving merge conflicts. Whoops.
=> Small Repairs

perma_web/perma/templates/user_management/stats.html, perma_web/perma/views/user_management.py
=> Add a couple figures to manage/stats page.

perma_web/api/views.py
Closes https://github.com/harvard-lil/perma/issues/2546
=> Handle users with "unlimited" link_limit in LinkBatch creation route

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock
=> Upgrade pytest-django-ordering

services/docker/webrecorder/wr.env
=> Silence noisy errors about connecting to shepherd 

docker-compose-travis.yml, docker-compose.yml, services/docker/webrecorder/nginx/nginx.conf
Will be necessary for new behavior being worked on in harvard-lil/perma#2569.
=> Upgrade to WR 4.3.0.

perma_web/perma/admin.py, perma_web/perma/settings/deployments/settings_prod.py, perma_web/perma/settings/utils/post_processing.py, perma_web/perma/tasks.py
Closes https://github.com/harvard-lil/perma/issues/2570 and, I think, closes https://github.com/harvard-lil/perma/issues/2551 (hard to confirm this locally without a lot of work)
=> Admin tweaks

docker-compose.yml
Should have no noticeable effect.
=> Use latest Perma Payments in dev.

perma_web/api/views.py, perma_web/perma/models.py
Observe the "TODO" about Cloudflare. 
There is probably some refactoring to be done here (keep the keys "wr_temp_username" and similar in Perma config? make this method more concise?), but I'm not sure.
Will close https://github.com/harvard-lil/perma/issues/2596
=> Handle link patch/replace with new WR integration.

perma_web/perma/models.py
Turns out https://github.com/harvard-lil/perma/blob/a01c9f8839122a88bfe636535a11bf9ef0f81591/perma_web/perma/models.py#L1365 takes care of it!
=> Remove TODO comment

services/docker/webrecorder/recorder_main.py
First pass at https://github.com/webrecorder/pywb/issues/471
=> Catch unicode decode exception; use fallback decoding.

services/docker/webrecorder/recorder_main.py
Hopefully there aren't others.... I should look into adding flake8.
=> Missed import.

docker-compose-travis.yml, docker-compose.yml, services/docker/webrecorder/app_main.py, services/docker/webrecorder/recordloader.py
We're still getting [these errors](https://github.com/harvard-lil/perma/issues/2605) on prod. I can't reproduce it locally for love or money... but I think this patching strategy should help.
=> Remove spaces by altering warcio source instead of monkeypatching.

services/docker/webrecorder/session.py
For when we are satisfied that the bugfix is reliably working.
=> SETEX: Remove noisy logging; just keep bugfix.

docker-compose.yml, services/docker/webrecorder/collection.py, services/docker/webrecorder/local.py, services/docker/webrecorder/recorder_main.py
This should handle https://github.com/harvard-lil/perma/issues/2614
It's not clear to me this architecture for the tempchecker is really working out.... but in the meantime, this should stop the error messages.
=> Address tempchecker race condition

perma_web/perma/templates/archive/iframe.html
Closes https://github.com/harvard-lil/perma/issues/2640. Thanks, jcushman, for reminding me about https://stackoverflow.com/a/38924601
=> Use Django's special escapejs filter.

perma_web/Pipfile, perma_web/Pipfile.lock
produced with `--keep-outdated`.... I've got some sleuthing to do to upgrade everything due to some mysteriously failing tests... kicking the can on that for a bit.
=> Upgrade Django and some background packages

services/docker/webrecorder/contentcontroller.py
Proof-of-concept solution for https://github.com/harvard-lil/perma/issues/2603
Let's chat with the WR about the right place to solve this.... since warcio has special code for dealing with this situation, this maybe should be solved by the warcserver, instead of the app....
=> Percent-encode non-ascii headers.

perma_web/static/bundles/create.js, perma_web/static/js/links-list.module.js
Closes https://github.com/harvard-lil/perma/issues/2655
=> Restrict search to the displayed folder.

perma_web/perma/views/common.py
closes https://github.com/harvard-lil/perma/issues/2646
=> If users manually request type=image, but no image present.

perma_web/static/bundles/create.js, perma_web/static/js/create-link.module.js
Closes https://github.com/harvard-lil/perma/issues/2535.
=> If you have zero personal links left, show "0" in the dropdown, not blank. 

perma_web/perma/models.py
Addresses half of https://github.com/harvard-lil/perma/issues/2574.
=> Detect, correct, and log the incidence of certain peculiar CaptureJobs.

perma_web/perma/templates/landing.html, perma_web/perma/templates/user_management/settings-tools.html
=> Fix bookmarklet and one link

perma_web/api/views.py
Fixes https://github.com/harvard-lil/perma/issues/2617 going forward.
=> Populate warc size in all situations

perma_web/perma/templates/email/registrar_user_ping.txt, perma_web/perma/templates/email/special.txt
The title, "Perma.cc: notes for law school registrars", was not in the text -- let me know if you want something different.
=> Update registrar ping email

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock
https://docs.djangoproject.com/en/2.2/releases/1.11.26/
=> Minor Django update

docker-compose.yml, perma_web/Pipfile.lock
https://github.com/jschneier/django-storages/issues/831, which we are experiencing presently on stage.
=> Update Django-Storages due to bug in 1.9

perma_web/perma/forms.py, perma_web/perma/tests/test_views_common.py, perma_web/perma/views/common.py, perma_web/static/bundles/global.css, perma_web/static/css/style-responsive.scss
As per https://github.com/harvard-lil/capstone/pull/1325/files
=> Add a trap for bots on the contact form.

perma_web/perma/views/common.py
…other codes via Django errors only.
=> Archive-Error route only intentionally returns 404 and 200... 

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock, perma_web/api/tests/test_link_authorization.py, perma_web/api/tests/test_link_resource.py, perma_web/api/urls.py, perma_web/functional_tests/tests.py, perma_web/lockss/views.py, perma_web/perma/admin.py, perma_web/perma/models.py, perma_web/perma/templatetags/local_datetime.py, perma_web/perma/tests/test_permissions.py, perma_web/perma/tests/test_static_bundles.py, perma_web/perma/tests/test_urls.py, perma_web/perma/tests/test_views_auth.py, perma_web/perma/tests/test_views_common.py, perma_web/perma/tests/test_views_user_management.py, perma_web/perma/tests/utils.py, perma_web/perma/utils.py, perma_web/perma/views/common.py, perma_web/perma/views/service.py, perma_web/perma/views/user_management.py
Let's give this a kick on stage, since this takes us through one major release and then two point releases. The changes are relatively minor, but....
We should keep an eye on background and beat celery tasks, which aren't exercised by the test suite.
=> Django 2.2

perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/views/common.py
....and a fix for a stupid mistake.
=> New setting, to fix private playbacks

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock
https://pypi.org/project/uwsgitop/
=> Add uwsgitop

.travis.yml, docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock, perma_web/perma/celery.py, perma_web/perma/settings/deployments/settings_common.py, perma_web/perma/settings/deployments/settings_prod.py, perma_web/perma/settings/deployments/settings_testing.py, perma_web/perma/settings/utils/post_processing.py, perma_web/perma/tasks.py, perma_web/perma/tests/test_capture_job.py
On my fork, the Travis build keeps hanging at `pipenv run fab dev.test_python:travis=True`. Tests run and pass fine locally. I'm interested to see what happens here.
=> Upgrade celery.

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock
Let's not push this to stage until the next production deployment.
=> Unpin some packages.

perma_web/perma/tasks.py
Closes https://github.com/harvard-lil/perma/issues/2731
=> Long-standing typo in capture teardown code

perma_web/perma/settings/deployments/settings_common.py
=> This was supposed to be in the background too.

perma_web/static/bundles/single-link-permissions.js, perma_web/static/bundles/single-link.css, perma_web/static/bundles/single-link.js, perma_web/static/css/style-responsive-archive.scss, perma_web/static/js/single-link.module.js
Closes https://github.com/harvard-lil/perma/issues/2068
=> Fix scrollbar on playbacks.

perma_web/perma/templates/archive/dark-archive.html
Closes https://github.com/harvard-lil/perma/issues/1830
=> Add link to Time Travel service for private link 403s.

perma_web/static/bundles/create.js, perma_web/static/js/links-list.module.js
closes https://github.com/harvard-lil/perma/issues/2514
=> Don't toggle Perma Link details when clicking links.

perma_web/perma/templates/archive/single-link.html, perma_web/perma/utils.py
closes https://github.com/harvard-lil/perma/issues/2750
=> Check for success before trying to download warc.

perma_web/perma/templates/email/admin/deletion_request.txt, perma_web/perma/views/user_management.py
Provide a link straight to the requesting user's account.
=> Tweak deletion email.

perma_web/perma/settings/deployments/settings_prod.py
Probably also needs a tweak in Salt.
=> Run IA upload and delete tasks hourly.

perma_web/perma/email.py
We've been seeing sporadic, single-instances of:
```
SMTPServerDisconnected at /some-route/
Connection unexpectedly closed
```
If emails fail to send, let's wait a second and try again.
=> Make two attempts to send emails.

perma_web/perma/templates/user_management/includes/paginator.html, perma_web/perma/templatetags/short_page_range.py, perma_web/static/bundles/global.css, perma_web/static/css/_bootstrap-mod.scss
=> Fix pagination on management pages.

perma_web/static/bundles/create.js, perma_web/static/js/folder-tree.module.js
=> Don't infinitely load folder tree, when no folder is selected.

perma_web/perma/models.py, perma_web/static/bundles/create.js, perma_web/static/js/create-link.module.js
The UI without the dropdown is a little weird, for sponsored users w/o orgs: for instance, your personal link count is displayed, no matter which folder you have selected. This is a little more natural.
=> Show the folder selection dropdown for sponsored users w/o orgs.

docker-compose.yml, perma_web/Pipfile.lock
https://docs.djangoproject.com/en/3.0/releases/2.2.14/
=> Package updates

perma_web/perma/views/user_management.py
=> Show correct template for {re, de}-activating sponsorships

perma_web/static/bundles/create.js, perma_web/static/js/links-list.module.js
Fixes https://github.com/harvard-lil/perma/issues/2821
=> Destroy infinite scroll waypoints when switching folders.

developer.md, docker-compose.yml, perma_web/perma/settings/deployments/settings_common.py, update_chrome.sh
I considered wrapping the script in git moves to branch and commit, but I'm not sure that's a good idea.
This will break if we change the Perma image numbering scheme or the capture user agent much.
=> Script for updating Chrome, and its first effects

perma_web/perma/views/common.py
Sometimes, Perma and WR have to do a cookie-setting handshake before we can play back an already-uploaded WARC for a client...... My understanding is that this only has to happen when a Perma Link is -private-.... but somehow we ended up in that flow for a public Perma Link, and the ensuing redirect loop (evidently not terminated by a user's browser) filled up a disk with logs. https://github.com/harvard-lil/perma/issues/2827
This PR displays an error message and sends an error email if that happens, instead of redirecting back to WR.
Let's see how often this actually happens. Hopefully, this logging will help us correlate with something in the WR logs, helping us track down the code path we traveled down.
=> Fail if a cookie is absent during WR playback handshake.

docker-compose.yml, perma_web/Pipfile, perma_web/Pipfile.lock
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst
=> A few more updates, including Pillow
