perma_web/perma/views/common.py

Simple tweak to respect the SECURE_SSL_REDIRECT=False setting when juggling SSL in the single link archive page. (This doesn't affect the live site, where SECURE_SSL_REDIRECT=True, but makes things less annoying for dev.)

Respect SECURE_SSL_REDIRECT=False

---

perma_web/api/authentication.py
perma_web/api/tests/utils.py

Tweak so you only need to pass in `api_key=<key>` for authentication, and don't also have to provide `username=<email>`.

Don't require email in API queries.

---

perma_web/mirroring/middleware.py
perma_web/mirroring/models.py
perma_web/mirroring/urls.py
perma_web/mirroring/utils.py
perma_web/mirroring/views.py
perma_web/perma/views/common.py
perma_web/perma/views/user_management.py

This isn't the javascript-based approach we discussed earlier, just patching up the existing technique for mirrors to pull up-to-date data from upstream during archive playback.
- Apply the same GPG auth we use for other inter-mirror communication.
- Fix the logic for forwarding to non-SSL version.

Fix upstream archive playback.

---

perma_web/perma/tasks.py
perma_web/requirements.txt

- Upgrade to latest pywb. Closes #770.
- Scroll up and down during capture to trigger any late-loaded page resources. This helps us on the acid test. Didn't see other low-hanging fruit; may as well call that good for now. Closes #771.

Archive tweaks.

---

perma_web/api/middleware.py
perma_web/mirroring/management/commands/runmirror.py
perma_web/mirroring/middleware.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/views/user_management.py
perma_web/requirements.txt
services/ansible/templates/django_settings.py.j2

- Stop api.perma.cc redirecting to dashboard.api.perma.cc.
- Rename confusing "MIRROR_USERS_SUBDOMAIN" to "DASHBOARD_SUBDOMAIN"

API subdomain redirection.

---

perma_web/api/resources.py
perma_web/fabfile.py
perma_web/perma/templates/js_config.html
perma_web/perma/templates/single-link.html
perma_web/perma/views/common.py
perma_web/static/js/single-link.js

- Allow authenticated API requests cross-domain from perma.cc to dashboard.perma.cc for the /archives/<id>/ get_detail endpoint. Fixes #785.
- Only show in-progress spinners for logged-in users (who should be the only ones who see single link pages immediately after creation anyway).
- Enable jsonp mode for /public/archives/ , per http://django-tastypie.readthedocs.org/en/latest/serialization.html . This still didn't work for me after a quick test, so there may be other changes necessary to allow cross-domain requests to that endpoint.

Cross-domain single-link page fixes.

---

perma_web/api/resources.py
perma_web/perma/middleware.py
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/storage_backends.py
perma_web/perma/templates/404.html
perma_web/perma/templates/500.html
perma_web/perma/templates/read_only_mode.html
perma_web/perma/utils.py
perma_web/perma/views/common.py
perma_web/static/css/style-responsive.scss
perma_web/static/maintenance/maintenance.html

This is an experimental read-only mode for deployments. The idea is that you can disable file and database writes by setting `READ_ONLY_MODE=True` during a deploy. People can still log in, view archives, etc., but get a pretty error message if trying to save anything.

Read-only mode for deployment.

---

perma_web/api/urls.py

This creates an identical version of the API at /v1a/ (for alpha). This way we can point the Word plugin at that while we're still thinking of making breaking changes, and if we do make breaking changes we can just switch that off and the plugin will display a pretty error message about needing to upgrade.

Add "v1a" API endpoint for alpha testing.

---

perma_web/api/validations.py

Our content-length limit was blocking PDFs over 1MB. We want to
check for PDF size as we stream. Removed the content-length
validation for PDFs.
There might be a better way, more unified way to look at archives
as we download? It feels like content-length is unreliable (the
host can set that value to anything they like in the header), and
if we check for mime-type, we're playing whack-a-mole (like I did
in this patch) and again, we're relying on the host to set the
proper value for content-type.
fixes #830

Ignore content-length when we see a PDF.

---

developer.md
install.md
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py
perma_web/perma/utils.py
perma_web/perma/views/service.py
perma_web/requirements.txt

- Use Wand for thumbnail creation. Check PNG size manually. Remove PIL dependency.
- Don't try to create PDF thumbnails in the thumbnail service -- it's messy to get right, and not scaleable. Just do it once in get_pdf.
- Temp files created by Wand will be deleted at the end of the get_pdf task.
- Only look at the first page of the PDF -- don't have Wand load up all the pages.

PDF thumbnail cleanup.

---

perma_web/perma/models.py

Fixes #628
(again).
nydailynews doesn't seem to respond reliably to HEAD requests -- sometimes it returns immediately, sometimes there's a long delay and we time out and refuse to archive.
Trying a GET request and dropping the connection when we get the headers should be more robust.

Use GET to check availability instead of HEAD.

---

perma_web/perma/tasks.py
perma_web/perma/templates/user_management/create-link.html
perma_web/static/js/create.js

- When an error occurs during PhantomJS capture, close out all open resources in a finally block. This should fix the lingering PhantomJS processes we've had.
- Handle a couple of specific cases that were interfering with captures (framesets, javascript that broke scrolling operations).
- Show an error message when capture fails (we were testing for image_capture!=='pending', but not image_capture=='failed').
Fixes #854.

Handle phantomjs capture errors.

---

perma_web/perma/tasks.py

The celery log was getting huge because warc captures were doing a ton of play-by-play logging, including a line for each resource in the page. This should cut those down.

Reduce celery logging.

---

perma_web/perma/models.py
perma_web/perma/tasks.py
perma_web/perma/templates/single-link.html
perma_web/perma/templates/user_management/created-links.html
perma_web/perma/utils.py
perma_web/static/js/links-list.js

This shows the favicon (for HTML captures only) in the folder view and on the single link page.
Not sure if we actually want to show it in those places, but it's fun to play with, and we can at least get it capturing so we can use it elsewhere later.

Fetch and display favicons for HTML captures.

---

perma_web/warc_server/pywb_config.py

Fix issue that caused existing WARC archives to show an error the first time they were displayed and CDX lines needed to be generated.

CDX generation returns queryset instead of list.

---

.travis.yml
developer.md
perma_web/perma/models.py
perma_web/perma/templates/user_management/includes/paginator.html
perma_web/perma/templates/user_management/manage_registrars.html
perma_web/perma/templates/user_management/manage_users.html
perma_web/perma/templates/user_management/manage_vesting_orgs.html
perma_web/perma/templatetags/current_query_string.py
perma_web/perma/templatetags/visible_vesting_orgs.py
perma_web/perma/utils.py
perma_web/perma/views/link_management.py
perma_web/perma/views/user_management.py

- Move vesting org list back to sql-based annotations, so sorting and pagination work again. Fixes #897.
- Refactor user_management so sorting, searching and pagination are handled by the same helpers functions for vesting orgs, registrars and users.
- Reduce number of sql queries required for lists.
- Add the "current_query_string" tag to simplify search/sort/filter/paginate interactions.
- In vesting user list, only show vesting org membership to registrars for vesting orgs belonging to that registrar. Fixes #889.
- As a bonus, vesting users viewing that list now see a list of orgs they have in common. Fixes #888.
- Users now see themselves in user list, with "(you)" next to their name.
- Fix "mysql has gone away" error we were getting at the end of Travis builds.

User management cleanup.

---

perma_web/api/resources.py

Before we made trailing slashes optional, the trailing slash on these urls meant that their loose regex patterns wouldn't match other url patterns because they'd end with "//". Now that the trailing slash is optional, they're gobbling up other url patterns

Make public key regex patterns more strict

---

perma_web/perma/tests/test_views_common.py
perma_web/perma/utils.py
perma_web/perma/views/common.py
perma_web/perma/views/service.py
perma_web/perma/views/user_management.py

So e.g. when a user submits something to the contact form, we get an email that's from info@perma.cc but Reply-To user-email, instead of from user-email.
This lets us use something like Amazon SES for email sending, which won't send emails from unverified addresses.

Use user-supplied emails as reply-to rather than from.

---

perma_web/requirements.txt

Upgrade from 1.7.6 to 1.7.10 — no code changes required.
There have been a couple of Django security updates since our last upgrade. Doesn’t look like anything important to us, but may as well grab the latest.

Upgrade to Django 1.7.10.

---

perma_web/perma/migrations/0018_auto_20150820_1249.py

Django for some reason insists we need to run makemigrations. The only result is to recreate indexes on a couple of fields. This does that, to make Django stop complaining.

Add missing migration.

---

perma_web/dev_requirements.txt
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_dev.py
perma_web/static/js/create.js

Thumbnails weren’t working for pages with favicons — we would try to generate the thumbnail when the only available capture was the favicon. D’oh.
Fixes #985.

Thumbnail fix

---

perma_web/perma/utils.py
perma_web/perma/views/common.py
perma_web/perma/views/service.py
perma_web/perma/views/user_management.py

This makes sure we don’t lose track of the user email now that it’s moved to Reply-To header instead of From.

Include user email and user agent in footer of all contact emails.

---

.travis.yml

See the [Travis-CI doc](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) about their new infrastructure. The biggest immediate gain (aside from whatever opaque magic they've added) is pip caching between builds.

Upgrade to new travis ci infrastructure

---

services/heroku/Procfile

These flags were recommended in a CloudAMQP email warning us that we were about to exceed our monthly allotment.

Disable celery features to avoid excessive msgs

---

perma_web/api/tests/test_link_resource.py
perma_web/api/tests/utils.py
perma_web/api/validations.py

Turns out spaces and fragments in URLs both work great (since `requests`, `phantomJS`, `pywb` etc already know how to handle them), except that our URL validator doesn’t like unencoded spaces. So this just encodes spaces for the validator and lets them proceed as usual.
Fixes #1003.

Allow spaces in submitted URLs.

---

perma_web/api/tests/test_link_resource.py
perma_web/api/tests/utils.py
perma_web/api/validations.py
perma_web/perma/tasks.py

Fix some edge cases during capture:
- Favicons and robots.txt load properly over SSL.
- Check for absolute `/robots.txt` instead of relative `robots.txt`. Update tests to make sure that robots.txt is found for URLs with sub-directories in the path.
- Display custom error message for URLs that cause redirect loops during capture, instead of 500 error.

Capture fixes.

---

perma_web/api/authorizations.py
perma_web/api/tests/test_link_authorization.py
perma_web/api/tests/test_link_resource.py
perma_web/fixtures/archive.json
perma_web/perma/models.py
perma_web/perma/templates/archive/single-link.html
perma_web/perma/views/common.py

Users can delete a link if it hasn't been sent to the archive network. We're no longer filtering on the vesting flag for deletes.
fixes #1059

Allow for deletion based on time window

---

perma_web/perma/views/common.py

If a user wasn't authenticated and they were viewing a record, they might see an error pop up during our new record check logic.
fixed.

Tiny fix when checking for new record

---

perma_web/static/js/links-list.js

Bug fix: link details expansion/collapse was forcing a scroll to the top. fixes #1084

Don't scroll to the top when link details are expanded/collapse

---

perma_web/perma/templates/user_management/created-links.html

Added a friendly note when the folder is empty, "This is an empty folder"
fixes #1086

Add a note when a folder is empty

---

perma_web/api/resources.py
perma_web/api/tests/test_link_resource.py
perma_web/perma/templates/user_management/create-link.html
perma_web/static/js/create.js

We needed the is_private value in the api response (we want to include an icon in the created links list to indicate to the user when a link is private)
fixes #1114

Surfaced is_private attribute in API

---

perma_web/fabfile/dev.py
perma_web/functional_tests/tests.py
perma_web/perma/tasks.py
perma_web/requirements.txt
perma_web/static/js/create.js

Sauce tests can now be run against a remote server with `fab dev.test_sauce:https://perma-stage.org`, or against your local server with `fab dev.test_sauce` if you have the sauce tunnel running.
Remember to run `pip install -r requirements.txt` in your local env to get the latest selenium -- or else captures might hang.

Get Sauce tests working again.

---

perma_web/perma/models.py

bug fixed.
This caused the record view screen to bomb. But, our tests didn't catch the issue. Yeowza!

We were erroring out when checking if if non-auth users could delete.

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/storage_backends.py
perma_web/perma/urls.py
perma_web/perma/views/common.py
perma_web/perma/wsgi.py
perma_web/requirements.txt
services/heroku/extra_requirements.txt
services/heroku/heroku_settings.py

This uses the WhiteNoise project for serving static assets, [which is recommended as a best practice by Heroku](https://devcenter.heroku.com/articles/django-assets). Static assets are now served by the same WSGI process that serves our Django app with no special handling needed, instead of a separate `/static` route in nginx or an S3 domain.
(We do still need to run collectstatic if DEBUG is off, as usual.)
On Heroku in particular, this is a win because the static assets end up bundled into the app slug. This way we don't have to re-run collectstatic when promoting a slug from perma-staging to prod.

Use whitenoise to deliver static assets

---

perma_web/perma/views/common.py

Complex sites take >1min to complete, so the new link bar doesn’t show. This bumps the new link bar up to 5 minutes but limits it to the user who created the link.

New link time

---

perma_web/perma/models.py

Use get_queryset instead of get_query_set to avoid that “RemovedInDjango18Warning: `BaseManager.get_query_set` is deprecated, use `get_queryset` instead.” warning we’ve been getting.

Avoid deprecation warning.

---

perma_web/perma/tasks.py
perma_web/perma/templates/archive/iframe.html
perma_web/perma/tests/assets/target_capture_files/test.html
perma_web/static/js/create.js

- Wait to forward user to success page until all captures have finished. Closes #1157
- Check for favicon tags is now case-insensitive (and our test now uses mixed case to make sure).
- Add "allow-same-origin" to sandbox. Drastically improves playbacks that depend on lots of JS includes.
- Speed up captures by about five seconds, by waiting only 1.5 seconds instead of 5 seconds for delayed post-load requests to start, and fetching favicons in a background thread.

Capture and playback fixes.

---

perma_web/api/tests/test_current_user_resource.py
perma_web/fixtures/archive.json
perma_web/perma/models.py
perma_web/perma/templates/archive/single-link.html
perma_web/perma/tests/test_views_common.py
perma_web/perma/tests/utils.py

- Add unit tests for the record page -- logged out and logged in, normal, dark archived, deleted.
- Fix 500 error for dark archived pages.
- Fix permissions checks to include dark_archived_robots_txt_blocked (although really we want to change to a `visible` flag and maybe a `visibility_reason` choicefield, right?)

Record page permissions and tests.

---

perma_web/requirements.txt
perma_web/warc_server/pywb_config.py

- Cache CDX lookups so we don't have to hit the database for each sub-resource when playing back a page.
- Close Django database connections in pywb playbacks (since they're outside a request and don't close manually).
This should fix instability we've been having on stage caused by exceeding max_user_connections.

More efficient playbacks.

---

perma_web/perma/templates/single-link.html
perma_web/requirements.txt
perma_web/static/pywb/vidrw.js
perma_web/static/pywb/wb.js
perma_web/static/pywb/wombat.js
perma_web/warc_server/pywb_config.py

Fixes a few issues with playbacks:
- allow-same-origin allows many page resources to load.
- return strings instead of unicode() from our CDX server so pywb doesn't choke on unicode urls.
- upgrade to latest pywb JS includes for better document.write support.
- patch pywb JS include to work with iframe and outside frame on different domains.

Improve playbacks.

---

perma_web/perma/admin.py
perma_web/perma/migrations/0023_auto_20151021_1840.py
perma_web/perma/models.py
perma_web/perma/templates/about.html
perma_web/perma/templates/includes/participating_institutions.html
perma_web/perma/templates/includes/partner_map.html
perma_web/perma/templates/landing.html
perma_web/perma/templatetags/carousel.py
perma_web/perma/urls.py
perma_web/perma/views/common.py
perma_web/static/css/style-responsive.scss
perma_web/static/js/map.js

- The partner logo carousel is now generated from the database instead of hardcoded. Logos are automatically thumbnailed and grayscaled so we don't have to upload tiny gray versions.
- The partner map is generated from the database instead of hardcoded in javascript. This requires running some sql to load the lat-lon for existing partners: https://www.dropbox.com/s/zipzrof9kh5kxtq/registrar_locations.sql?dl=0
(todo: update the fixtures so the map and carousel show something on stage)

Partner display improvements.

---

perma_web/perma/views/user_management.py

When a user left an org, we weren't redirecting to the right page. We now redirect to sensible pages and provide a confirmation
message.
fixes #1194

Redirect to correct page when user leaves org

---

perma_web/perma/templates/user_management/manage_registrars.html

Chrome will try to validate our forms for us. Kind of weird. So, when we mark a form field as a url, Chrome will validate and block submission unless you add a novalidate tag to the form.
Since we're forgiving with our url field on the create page, maybe we should be here too? Added the novalidate tag (for the url) in the registrar form.
fixes #1183

Tell Chrome to not validate form

---

perma_web/perma/models.py
perma_web/perma/templates/archive/single-link.html
perma_web/perma/tests/test_views_common.py
perma_web/perma/views/common.py

- Fix missing privacy toggle button for some users. Closes #1234.
- Clarify message about who can see private link contents. Closes #1236.

Link privacy tweaks.

---

perma_web/static/js/single-link.js

This addresses the javascript part of #1245.
- Improved javascript calculation of iframe height (based on the top of the iframe instead of the bottom of the header). Removes double scrollbar in multiple browsers.
- Iframe is resized on window resize.

Improved single link iframe sizing.

---

perma_web/perma/templates/archive/single-link.html

Just a first pass at this -- we can do more later if we like.

Show upload vs. capture status on record page.

---

perma_web/perma/templates/archive/single-link.html
perma_web/perma/templates/js_config.html
perma_web/perma/tests/test_views_service.py
perma_web/perma/urls.py
perma_web/perma/views/service.py
perma_web/static/css/style-responsive-archive.scss
perma_web/static/js/global.js

Unused route receive_feedback and all associated methods in service.py and globals.js
Feedback modal used to exist here: https://github.com/harvard-lil/perma/blob/7af51069e1d97d35ff0366e494eb95a4dcebdfb5/perma_web/perma/templates/base-responsive.html#L131 but it seems that we have gotten rid of it and are instead routing users to /contact.
Finishes #1342

Remove feedback form

---

perma_web/perma/templates/archive/single-link.html
perma_web/static/css/style-responsive-archive.scss
perma_web/static/js/single-link.js

Just a little tweak so that the width of the “Your new Perma Link is” box on the new-link page matches the actual length of the URL.

Url width on new-link page.

---

perma_web/api/resources.py
perma_web/perma/models.py
perma_web/perma/templates/user_management/create-link.html

- Reduces SQL queries for /organizations API endpoint from `org_count*2` to 1.
- Reduces SQL queries for create page from `org_count*2 + folder_count` to `org_count` (5287 queries to 560 queries if user is an admin)

Optimize folder views.

---

perma_web/fabfile/deploy.py

This makes the mysql backup step in `fab deploy` much faster by skipping backup of the `cdxline` table, which is just a cache that can be recreated if necessary.

Skip cdxline in backup.

---

perma_web/perma/models.py

Make get_orgs return a queryset in all cases so `get_orgs().select_related()` works.

Return queryset from get_orgs.

---

perma_web/api/resources.py
perma_web/perma/admin.py
perma_web/perma/migrations/0030_auto_20160224_2212.py
perma_web/perma/migrations/0031_merge.py
perma_web/perma/models.py
perma_web/perma/templates/user_management/manage_orgs.html
perma_web/perma/tests/test_permissions.py
perma_web/perma/views/user_management.py

- Org delete is now a flag, like link delete.
- Deleted orgs and links stay visible in admin.
- Add "DeletableModel" and "DeletableManager" to abstract the delete-flag pattern.
- Use `accessible_to(request.user)` to enforce access permissions in org views.

Re-enable delete for orgs.

---

developer.md
perma_web/perma/tasks.py
perma_web/perma/utils.py
perma_web/perma/views/common.py
perma_web/perma/views/service.py
perma_web/perma/views/user_management.py

- Encapsulate email sending into `send_user_email` and `send_admin_email`. All email sending should go through one of these.
- Fixes bug with court emails coming from the wrong address.
- Also remove some unused imports.

Improve email handling

---

.travis.yml
perma_web/functional_tests/tests.py
perma_web/perma/tasks.py
perma_web/perma/tests/test_permissions.py

This hopefully fixes the timeout on that one test by using Firefox instead of PhantomJS to run the integration tests.

Fix test timeouts

---

perma_web/perma/tasks.py

Hi,
looking through your tasks.py I noticed that there's a bug that prevents additional attempts to get the title:
def get_title():
if browser.title:
save_fields(link, submitted_title=browser.title)
This grabs browser.title, which may contain the correct title or '' (which evaluates to False) - but it never raises an Exception! [1].
Hence, the subsequent `repeat_while_exception(get_title, timeout=10)` will never get a chance to repeat.
This tiny patch just raises a KeyError for empty titles, allowing for retries of up to 10 seconds.
[1] http://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html#WebDriver.title

Fix retry on getting browser title

---

perma_web/api/authorizations.py
perma_web/api/resources.py
perma_web/api/tests/test_current_user_authorization.py
perma_web/api/tests/test_link_authorization.py
perma_web/api/tests/test_link_resource.py
perma_web/api/urls.py
perma_web/perma/admin.py
perma_web/perma/migrations/0003_capturejob.py
perma_web/perma/migrations/0004_auto_20160506_1632.py
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py
perma_web/perma/templates/docs/developer/index.html
perma_web/perma/templates/docs/developer/toc.html
perma_web/perma/templates/user_management/stats.html
perma_web/perma/tests/test_capture_job.py
perma_web/perma/views/user_management.py
perma_web/static/js/create.module.js

This pull req creates a custom queue for our background capture jobs, stored in a separate model called CaptureJob with a one-to-one relationship to Link.
Changes:
- Jobs are processed round-robin, one per user, so a single user can't flood the queue.
- Jobs submitted from the website are processed before jobs submitted from the API. (API users can join the human queue by passing `human=1`, which could make sense if there's a human waiting for that particular capture -- sort of an honor system thing.)
- CaptureJob tracks start time, end time, and attempts, so we can measure how fast we are for captures and how long people are waiting in the queue.
- CaptureJob tracks current capture status, so we can show a real-time progress bar to users waiting for a capture. We can also show where a …

Custom queue for capture jobs

---

perma_web/perma/templates/email/user_added_to_registrar.txt

Registrar-upgraded email template in my last pull wasn’t filling in the registrar name properly, d’oh.

Fix email template

---

perma_web/perma/migrations/0001_initial.py

Link_id only needs to be 255, not 2100. This avoids the 'Specified key was too long; max key length is 767 bytes' error on new databases.
Putting this in the initial migration because I’m not sure we want to apply it to prod — might take a zillion years to run.
Fixes #1501

Set initial link_id length to 255

---

perma_web/api/resources.py
perma_web/perma/migrations/0006_add_internetarchive_status.py
perma_web/perma/models.py
perma_web/perma/tasks.py

- we're now storing ia upload status on link models
- retrying to upload if warc exists but ia upload failed for some reason
- not retrying if warc does not exist (marking link as failed permanently)
- if archive WAS uploaded but later was deleted (made private, for instance), only the file was getting reuploaded. the metadata was not. this is now fixed — we're checking if item exists and then applying "modify_metadata" method if it's been "Removed".
I think we might need to think a little more about how we're dealing with IA. If a warc has failed to be created, do we want the metadata stored somewhere? What are all the edge cases, do we do a good job in keeping perma archives and internet archive archives in sync?

internet archive metadata + status fixes

---

perma_web/fabfile/dev.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/requirements.in
perma_web/requirements.txt
perma_web/spec/javascripts/create.module.spec.js
perma_web/spec/javascripts/error-handler.spec.js
perma_web/spec/javascripts/global.setup.spec.js
perma_web/spec/javascripts/helpers/mock-ajax.js
perma_web/spec/javascripts/support/jasmine.yml
perma_web/static/js/create.module.js
perma_web/static/js/error-handler.js
perma_web/static/js/helpers/dom.helpers.js
perma_web/static/js/helpers/general.helpers.js

beginning of JS unit tests! 
- added jasmine library (and jasmine ajax)
- added requirements
- added tests for create module / beginning of tests for error and general modules
- added DOMHelpers module, which is where any DOM modification should go. No other DOM modification should happen elsewhere. 
- added localStorage helpers to general helpers to silo it out for easier testing / DRY code
- to call jasmine in shell: `fab dev.jasmine`, go to 0.0.0.0:8888 to see output in your browser
- you can conversely call `jasmine-ci --browser phantomjs` for shell output
TODO: coverage report, integration into travis
finishes #1534

Js unit tests

---

app.json
perma_web/Procfile
perma_web/perma/wsgi.py
perma_web/requirements.in
perma_web/requirements.txt
services/heroku/extra_requirements.txt
services/newrelic/newrelic.ini

This pulls out our Heroku-specific New Relic support, and adds general New Relic support that can be enabled with an environment variable. Based on Jay's pull request but adapted to play well with stage/dev as well as prod.

Newrelic integration

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/archive/base-archive-responsive.html
perma_web/perma/templates/archive/single-link.html
perma_web/perma/views/common.py
perma_web/spec/javascripts/single.link.permissions.module.spec.js
perma_web/static/css/style-responsive-archive.scss
perma_web/static/js/single-link-with-permissions.js
perma_web/static/js/single-link-with-permissions.module.js
perma_web/static/js/single-link.module.js

also includes: 
- not sending any scripts to user if user has no editing permissions 
- moved full date to top blue bar (otherwise it was getting repeated in the archive info dropdown)
- moved updating archive with image to general archive info dropdown. Not showing another modal on top.
finishes #1519

edit archive attributes in one place

---

perma_web/static/js/single-link-permissions.module.js

- only showing save status for edited field
- removing save status after a few seconds
- not firing change on input blur
- not firing change on no input change (checking old input values before firing)
fixes #1588

single link save status

---

perma_web/api/tests/test_link_authorization.py
perma_web/api/tests/test_link_resource.py
perma_web/api/tests/utils.py
perma_web/perma/settings/deployments/settings_heroku.py
perma_web/perma/settings/deployments/settings_prod.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tests/test_capture_job.py
perma_web/perma/tests/utils.py
perma_web/requirements.in
perma_web/requirements.txt
perma_web/warc_server/pywb_config.py

- Lazy load models in pywb_config.py -- Django 1.9 is more picky about how soon you can import models.
- Upgrade django-redis to 4.4.3.
- Set tests to use django-redis and fakeredis so this error wouldn't make it past our tests next time.

Fix Django 1.9 errors on stage

---

perma_web/Procfile

This is a first cut at monitoring celery with NewRelic on staging. It'll monitor celery and the Django application together; next step is to monitor them separately.

Monitor celery on staging

---

perma_web/perma/tasks.py

Not sure if this is correct, but I don't know how to trigger this.
Trying to add fix for this stack trace:
```
Task perma.tasks.upload_to_internet_archive with id 4529afb4-c853-410c-a633-4e6f244128d4 raised exception:
'ConnectTimeout(u"Error retrieving metadata from https://archive.org/metadata/perma_cc_T8FC-AKFK, HTTPSConnectionPool(host=\'archive.org\', port=443): Max retries exceeded with url: /metadata/perma_cc_T8FC-AKFK (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f12649b7a50>, \'Connection to archive.org timed out. (connect timeout=12)\'))",)'
Task was called with args: [] kwargs: {u'link_guid': u'T8FC-AKFK'}.
The contents of the full traceback was:
Traceback (most recent call last):
File …
```

fix - attempting to catch internet archive connection errors

---

perma_web/perma/admin.py
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/requirements.in
perma_web/requirements.txt

This adds basic tagging for registrars. We can use this for stuff like tracking counts of law school registrars, court registrars, etc.

Tagging for registrar model

---

perma_web/perma/templates/500.html
perma_web/perma/templates/user_management/manage_orgs.html
perma_web/perma/templates/user_management/manage_registrars.html
perma_web/perma/templates/user_management/manage_users.html

... so user won't get an error if they're on page two of a list and add a filter that results in fewer than two pages of results.
This also softens the 500 page by removing the "you broke perma.cc" message.

Reset pagination for sort and filter buttons

---

perma_web/perma/tests/test_permissions.py
perma_web/perma/views/user_management.py

- Refactor our limited_login view to wrap Django’s builtin login view rather than duplicating it.
- Add a check that forwards the user from the login page if they are already logged in.
Fixes #1593

Redirect logged in user on login page

---

perma_web/perma/views/service.py

Currently, if you use the bookmarket while logged out, the url gets lost during the redirect from the login form because it is url-encoded. 
Doesn't work: https://perma.cc/login?next=/manage/create%3Fv%3D1%26url%3Dhttps%253A%252F%252Fgithub.com%252Fharvard-lil%252Fperma%252Fissues%252F457
Works: https://perma.cc/login?next=/manage/create?url=https://github.com/harvard-lil/perma/issues/457
This tweaks the redirect url returned by the bookmarklet service so it works for logged-in and not-logged-in users.

Tweak redirect for not-logged-in bookmarklet users

---

perma_web/perma/templates/user_management/create-link.html
perma_web/perma/views/link_management.py
perma_web/static/css/style-responsive.scss
perma_web/static/js/admin.js
perma_web/static/js/helpers/general.helpers.js

Per https://github.com/harvard-lil/perma/issues/457
If a user navigates straight to /manage/create/, an advertisement for our browser tools is shown. If a user arrives at /manage/create having used the bookmarklet or a browser extension, the advertisement is not displayed.
When a user dismisses the ad, a cookie is created that hides the ad on that browser for 120 days.
Appearance for org users:
Appearance for regular users:

Show dismissible ad for browser tools on create page

---

perma_web/perma/tasks.py

This solves a problem exposed when changing from RabbitMQ to SQS: 
`'<MaybeEncodingError: Error sending result: \'\'[<Response [200]>]\'\'. Reason: \'\'TypeError("can\\\'t pickle generator objects",)\'\'.>'`

Just return from upload_to_internet_archive

---

perma_web/static/js/links-list.module.js

- Avoid throwing javascript errors caused by treating API errors as successes.
- Avoid showing “empty folder” message if infinite scrolling query returns no additional results.

Link folder tweaks

---

perma_web/api/tests/test_link_validation.py
perma_web/api/validations.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py
perma_web/perma/utils.py

- Capture size limits: uploads and captures now share the same size limit, set by `MAX_ARCHIVE_FILE_SIZE`.
- All requests made by warcprox must comply with our IP blacklist.
- Capture times are tightened up. New capture time limits: *something* must finish loading within 45 seconds, and then if any requests are still pending at that point, they get an additional 30 seconds.
- Audio/video background captures will be counted toward the size limit and will be stopped by the time limit, so infinite streams don't result in infinite captures.

Web capture improvements

---

perma_web/perma/views/user_management.py

Don't create a pending registrar if the submitted user form is invalid.
https://github.com/harvard-lil/perma/issues/1740
Also removes a couple unused lines of code.

Library signup form tweaks

---

perma_web/api/resources.py
perma_web/fixtures/folders.json
perma_web/functional_tests/tests.py
perma_web/perma/migrations/0017_rename_mylinks_to_personallinks.py
perma_web/perma/models.py
perma_web/perma/templates/docs/developer/index.html
perma_web/perma/templates/docs/perma-link-creation.html
perma_web/perma/templates/user_management/create-link.html
perma_web/perma/views/link_management.py
perma_web/static/css/style-responsive.scss
perma_web/static/js/create.module.js

- dropdown color changes
- "unlimited" badge 
- "My Links" to "Personal Links"
- warning message for org users nearing their personal limits
N.B. change to perma_web/perma/templates/docs/developer/index.html
Do we anticipate anybody using our API relies on a folder being called "My Links"? Surely not.

Nudge org users to use org folders

---

perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

Let modal stay at top of screen instead of non-working vertical centering

Modal position fix

---

perma_web/requirements.in
perma_web/requirements.txt

We could upgrade to 3.4.0, but I thought I'd try the minimum necessary change.

Upgrade Pillow to 3.3.2

---

perma_web/static/bundles/create.js
perma_web/static/js/create.module.js

Org users should get a warning message once, when their Personal Links folder is selected and when they have 3 personal links remaining.
(Previous behavior: warning appeared on every page load of the create page if the org user had 3 personal links remaining, regardless of what folder was selected and regardless of whether they'd been warned before. Whoops.)

Fix warning messages

---

perma_web/perma/templates/docs/faq.html

Closes #1827.
Let me know if you have any feedback on this change or if there’s something I missed.

Removed the link to #faculty on the FAQ page

---

perma_web/fabfile/deploy.py

Makes sure that installed packages match requirements.txt — no extras. Avoids problems with src packages masking site-packages or vice versa.

Use pip-sync for deploys

---

perma_web/perma/email.py
perma_web/perma/forms.py
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/contact-thanks.html
perma_web/perma/templates/contact.html
perma_web/perma/templates/email/registrar_contact.txt
perma_web/perma/tests/test_email.py
perma_web/perma/tests/test_views_common.py
perma_web/perma/urls.py
perma_web/perma/views/common.py

All is unchanged for not-logged-in users, regular users, and registrar users.
Org users associated with a single org still see the normal contact form, but a hidden field naming their registrar is included in the form:
Org users associated with multiple orgs are presented with a drop down list:
If, in config, CONTACT_REGISTRARS = True (False by default via common.py), then when the form is submitted, an email is sent to all the active registrar users associated with the org, and both Perma and the sender are cc'ed. And, the user is delivered at a customized thank you page, listing the names and email addresses of everyone who has been emailed:
In all other situations, an email is sent to Perma as usual, and the normal thanks page is displayed.

Send contact form messages from org users to registrar users 

---

perma_web/perma/models.py
perma_web/perma/templates/user_management/activation-email.html
perma_web/perma/templates/user_management/manage_users.html
perma_web/perma/tests/test_permissions.py
perma_web/perma/tests/test_views_user_management.py
perma_web/perma/urls.py
perma_web/perma/views/user_management.py

1) If an unconfirmed/inactive user tries to reset their password using the reset password form, they are forwarded to the "Your account is not active, click here to resend your activation email" page. Old behavior: password reset form informs the user it was successfully submitted, and that they'll will a password reset email, which is not true.
2) Adds a button next to unconfirmed/inactive users on the /manage/{users, organization-users, registrar-users} pages.
It resends their activation email, and takes you to a confirmation page.

Activation email tweaks

---

perma_web/perma/templates/403.html
perma_web/perma/tests/test_permissions.py
perma_web/perma/utils.py
perma_web/perma/views/error_management.py
perma_web/perma/views/user_management.py

Currently, if you are logged in and attempt to access a resource you don't have permission to access (e.g. test_user@example.com tries to access /manage/stats), you are redirected to the login form. The login form perceives that you are already logged in, and redirects you to the page you started at. Lather, rinse, repeat.
Here, you get a 403 "Forbidden" error instead, and are directed to a styled error page.

Users lacking permission get 403s

---

perma_web/api/tests/test_link_validation.py
perma_web/api/validations.py

Fixes https://github.com/harvard-lil/perma/issues/1841

Handle long unicode strings passed as URLs to link creation api

---

perma_web/fabfile/dev.py
perma_web/perma/email.py
perma_web/perma/tests/test_email.py

Instead of sending to all eligible registrar users, allow filters to be passed in to the fab task:
limit_to, limit_by_tag, exclude, and exclude_by_tag
This gives us a little more control over the sending process, including the ability to send a test email in production, just to be extra careful, and the ability to resend to an arbitrary subset of registrars' users.

Tweak to task for sending the email that pings registrar users

---

perma_web/fabfile/dev.py
perma_web/perma/email.py
perma_web/perma/models.py
perma_web/perma/templates/email/registrar_user_ping.txt
perma_web/perma/tests/test_email.py
perma_web/perma/tests/test_models.py

Since we're in January, we want to be able to send registrar users 2016 stats instead of 2017. Add some abstraction and parameters to make that possible.

Generalize year for registrar users' stats

---

perma_web/fabfile/dev.py

To improve default experience in dev box. This memory leak is a drag. (At least they TELL us they know there's a memory leak.)

Revert change included 0a5d191

---

perma_web/perma/templates/user_management/stats.html
perma_web/perma/views/user_management.py

Re: #1802, this should show the timings for the fastest 5%, 50%, and 95% of captures for each day on the admin stats page.

Show range of capture times on admin stats

---

perma_web/perma/templates/archive/single-link.html
perma_web/perma/views/common.py

image meta tag fails for both twitter and facebook
to fix the warning: `Object at URL 'https://perma-dev.org/CD3H-CCV3' of type 'website' is invalid because the given value 'perma-dev.org/static/img/sharing/blue_logo.png' for property 'og:image:url' could not be parsed as type 'url'.
`

fix - added http protocol to image url metatag

---

perma_web/fabfile/dev.py
perma_web/warc_server/pywb_config.py

Fixes #1917
@rebeccacremona: check out the tweak to `fab run` here. To test this I had to set DEBUG=False, which I realized is incompatible with running webpack in the background. So I threw in a conditional for that and also a conditional for the celery background task. Does checking RUN_TASKS_ASYNC seem like a good approach here?

Fix pywb django templates

---

perma_web/perma/tasks.py

We're getting way too many failures here. ~115 out of the 160 links currently "private due to meta tag  analysis failure" are from sites other than NYTimes. All the non--NY Times links that I've spot checked so far can be made public.
In all cases, the problem seems to be that the page runs large numbers of slow-loading ad libraries and trackers that each significantly alter (or replace entirely?) the document head, possibly even rewriting the entire document. I suspect there is something improper about their behavior, but I can't pin it down. (But even if I did, I don't think we can work around it.)
I'm hoping if we wait longer (increasing the upper bound from from 10 to 30 seconds), this will happen much less frequently.
If it doesn't, we might want to revisit our approach.

wait longer for metatags

---

perma_web/api/tests/test_folder_resource.py
perma_web/api/tests/utils.py
perma_web/api/validations.py
perma_web/static/bundles/create.js
perma_web/static/js/folder-tree.module.js

- Fix folder drag and drop problem reported by Adam.
- Handle case where second folder is created/dragged/renamed so as to end up with same name as existing folder.
- Unexpected jstree errors (such as duplicate folder errors) will be reported to user instead of swallowed, so we don't have things fail for no apparent reason.
- Refactor API test helpers to avoid duplication in rejected_<request method> functions.

Folder drag fix

---

perma_web/static/bundles/create.js
perma_web/static/js/folder-tree.module.js

Fixes an edge case where folders couldn't be moved into closed folders with subfolders

Disable hover open in jstree

---

perma_web/perma/templates/user_management/stats.html
perma_web/perma/views/user_management.py

MINOR: count links tagged as meta-tag-failures on the stats page.

---

perma_web/api/resources.py
perma_web/dev_requirements.txt
perma_web/perma/tests/test_admin.py
perma_web/requirements.in
perma_web/requirements.txt

Upgrade django-admin-smoke-tests, django-model-utils, and django-mptt to versions compatible with Django 1.10.
Also tweaks the Tastypie API code to be compatible with the next version if we ever move to it.

Upgrade packages in preparation for Django 1.10

---

perma_web/fixtures/users.json

Just a small tweak — this avoids the warning messages about timezones that we always get when starting to run the tests.

Avoid timezone warnings in fixtures.

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_prod.py
perma_web/perma/tasks.py
perma_web/perma/templates/user_management/stats.html
perma_web/perma/views/user_management.py

Currently when link capture times out after 5 minutes (resulting in a `kill -9` of the celery worker), we get an error email and the link stays pending/in_progress forever.
If we set a slightly shorter soft timeout, celery lets us catch the SoftTimeLimitExceeded error, tag the link as timed out, and set link status to failed.
This pull also shows the count of timed-out links on the admin stats page.
In theory we could add tests for all this as well, by running a capture task with a very short soft_timeout. I think that test wants to live in api2/tests, which is currently under construction, so I didn’t write it …

Tag links with capture timeouts

---

perma_web/api/resources.py
perma_web/perma/middleware.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/signals.py
perma_web/perma/storage_backends.py
perma_web/perma/utils.py

I added this “read only mode” idea a couple of years ago, and we never used it. The general notion was to be able to set the server to stop writing to the database but otherwise keep running, which would in theory let us handle many updates without going into full maintenance mode, without worrying about data integrity. Given that it hasn’t been looked at or thought about in a couple years and I’m not confident it works correctly or does anything useful, let’s pull it out.

Remove read only mode

---

perma_web/dev_requirements.txt
perma_web/fabfile/dev.py

Use master branch of django-extensions for now, with support for `--reloader-type stat`, to fix hot reloading for Django test server.

Fix django-extensions runserver_plus reloading

---

perma_web/fabfile/dev.py
perma_web/functional_tests/tests.py

Functional tests can be run against a remote server with `SERVER_URL=https://perma-stage.org fab test:functional_tests`. This gets that working again.

Fix functional tests against remote server

---

perma_web/perma/models.py

I don't think `write_warc_metadata_record` is used anywhere. If it's worth keeping for historical interest, maybe we can comment it out like `get_thumbnail` about 100 lines earlier.

Remove unused function

---

perma_web/perma/tasks.py

The behavior of attempted captures of Forbes.com recently changed, and multiple users have contacted us about it. Captures fail very early in the capture process, and as a result, users aren't presented with the normal "capture failed" screen, nor given a chance to upload their own PDF.
This pull request addresses one component of this bad experience: if warcprox throws an exception while trying to proxy a request, we should remove the corresponding request and response from our list of proxied requests and proxied request/response pairs. As is, if the very first request/response fails in this way, the capture gets stuck forever here, regardless of the success of any other requests:
```
while not have_response:
if proxied_responses:
for request, response in proxied_pairs:
if response is …
```

Warcprox exception handling (workaround one problem with forbes.com)

---

perma_web/perma/tasks.py

Introduces a mechanism for running special code during the capture process for particular domains. 
Delays captures of forbes.com for up to 24s, the apparent minimum time to bypass the splash page. (Made 10 sequential successful captures locally.)
Only relevant if 1992 is also merged.

Domain special handling

---

perma_web/perma/admin.py
perma_web/perma/templates/user_management/stats.html
perma_web/perma/views/user_management.py
perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

More tags on stats page; link from stats page to filtered view of link admin:
Include capture job on bottom of link's admin page, read-only except for status:

Show more link info to admins

---

perma_web/perma/tasks.py

Only apply meta-analysis-failed tag at the end of the capture process. This way, the tag could get applied twice, or could incorrectly get applied if the browser crashes during our second, post on-load attempt at retrieving meta tags, regardless of whether the first attempt succeeded or not.

Incorrect tagging

---

perma_web/static/bundles/create.js
perma_web/static/js/create-link.module.js

See https://github.com/harvard-lil/perma/issues/1994
We show something like this when a capture fails before being handed to tasks.py:
If it fails during the task, though, we show this:
Swap out the latter for:

Tweak: show upload button on capture failure

---

.gitignore
perma_web/perma/tasks.py

This improves our support for setting `CAPTURE_BROWSER = 'Chrome'`, primarily by allowing Chrome to take full-page screenshots.
This pull includes some refactoring but should not substantively affect PhantomJS captures, except for one change -- the page size for screenshots is based on measuring the size of `<html>` instead of `<body>`, since the former can be larger than the latter.
This does not yet take advantage of Chrome's new `--headless` flag. It's just using Selenium's longtime support for controlling desktop browsers along with a virtual display. `--headless` with Selenium/ChromeDriver doesn't seem to work reliably yet. (As of Chrome 59/ChromeDriver 2.29 -- next stable release of both might be good.) But I think that's just a two-line switch once `--headless` is ready, and the …

Improve Chrome support

---

perma_web/api/tests/test_link_resource.py
perma_web/perma/tasks.py
perma_web/perma/tests/assets/target_capture_files/test_media_a.html
perma_web/perma/tests/assets/target_capture_files/test_media_b.html
perma_web/perma/tests/assets/target_capture_files/test_media_c.html
perma_web/perma/tests/assets/target_capture_files/test_media_outer.html

This updates the run_in_frames_recursive function to switch to frames by numeric index rather than fetching and using WebElement references. The primary advantage is we don't get expired WebElement references on pages that keep rewriting their HTML. Also saves a couple of find_element calls per recursion.
Other improvements while refactoring:
- Recursion is now limited to depth of 3, and 20 iframes visited overall.
- Check for non-http iframes and skip.
- Avoid 1 redundant tree traversal in each recursion, by putting traversal at the end of the loop instead of the beginning.
On the testing side, this pull consolidates two tests that were hitting the same nested-frame endpoint, and expands that test to look for media elements across a more complicated iframe hierarchy.
Unrelatedly (except …

Improve run_in_frames_recursive function

---

perma_web/api/tests/test_link_resource.py
perma_web/perma/site_scripts.py
perma_web/perma/tasks.py
perma_web/perma/tests/assets/target_capture_files/test.html
perma_web/requirements.in
perma_web/requirements.txt

The primary change here is to extract page contents by fetching the whole DOM and inspecting with PyQuery, rather than using multiple calls to Selenium to inspect individual elements.
The general approach now becomes:
- `dom_tree = get_dom_tree(browser)`, which is a slow function that calls out to `browser.execute_script` and returns a parsed PyQuery object.
- Inspect `dom_tree`, which is basically free.
This doesn't seem to be much faster (or slower) in practice, but it simplifies things in a few different ways:
- Use python instead of javascript to extract data, without loss of speed.
- Lots fewer calls to `browser` makes it easier to reason about performance -- slow steps are isolated to `get_dom_tree`.
- Lots fewer calls to `browser` will make it easier to migrate to raw Chrome …

Extract page contents by parsing DOM.

---

perma_web/perma/tasks.py

Whitespace, and fix for one tiny discovery: the browser often crashes during NYTimes captures while waiting for the onload event. If that happens, we currently still try to find the post-load function and run it, which causes an exception with a lengthy stacktrace that it would be better to keep out of the logs. This throws in yet one more with "browser_running" to hide that.

Trivial tweak to latest tasks.py

---

perma_web/perma/templates/user_management/manage_users.html

Fix for https://github.com/harvard-lil/perma/issues/2018
(Though note: we previously decided to remove this functionality entirely, since user link counts include every link created by that user, not the links the've created for that org. Work on that, and removal/alteration of similar features, is still in progress)

FIX: link count filter name changed in 384bc9

---

perma_web/perma/tasks.py

Working on https://github.com/harvard-lil/perma/issues/2019
This doesn't kill the threads when the capture is over, but at least lets us quit the dev server locally in the normal way.

first pass at killing leaking threads

---

perma_web/perma/tasks.py

First pass workaround for captures where js is disallowed by content security policy.
@jcushman suggests a better approach for the future is to move to Chrome's remote debugger protocol (`--headless --remote-debugging-port=9222`, https://developers.google.com/web/updates/2017/04/headless-chrome))

Working on #2021

---

perma_web/perma/templates/archive/single-link.html
perma_web/perma/templates/docs/faq.html
perma_web/perma/views/common.py
perma_web/requirements.in
perma_web/requirements.txt
perma_web/warc_server/pywb_config.py

This pull req suggests a way to prepend our warcs with some metadata that helps wr player display the archive in a more helpful way
We only prepend to the warc as we're streaming it to the client, and we only prepend rarely, when the request type is warc_download
Thanks for the help @ikreymer!
Also added a download button in the record details tray -- need to refine this button ux/ui in the tray

Added improved support for Webrecorder Player

---

perma_web/fabfile/dev.py
perma_web/perma/templates/archive/download_to_view_pdf.html
perma_web/perma/templates/archive/single-link.html
perma_web/perma/tests/test_views_common.py
perma_web/perma/utils.py
perma_web/perma/views/common.py

fixes #2056 
Showing "view/download" button on any mobile device when viewing a PDF

Pdf mobile

---

.travis.yml
perma_web/functional_tests/tests.py
perma_web/requirements.in
perma_web/requirements.txt

In order to upgrade `cryptography`, I started by upgrading `requests`, and then had a small chain of additional package upgrades in order to get pip-compile to complete. In the end, cryptography was still set at 1.8.1, so I specified the version by hand in `requirements.in`, and left the other upgrades in place. Then, on testing, I saw an occasional error (`selenium OSError: [Errno 9] Bad file descriptor`) on teardown of phantomjs, so I adjusted the teardown functions according to https://stackoverflow.com/a/45786385/4074877.
Fixes #2130.

Upgrade requests and other packages, tweak teardown for functional tests

---

developer.md
perma_web/requirements.in
perma_web/requirements.txt

So I think we haven't quite been using pip-tools right -- we're supposed to specify versions only in `requirements.txt`, not in `requirements.in`. This still pins versions, but lets us use `pip-compile` to upgrade a package and all dependencies just by running something like `pip-compile -P celery`.
In this pull req:
- update pip-tools to latest
- drop all version numbers from requirements.in
- update pytz (this is the only version that actually changed as a result of dropping version numbers, which I think was because it had a weird `2013b` version number and can safely be ignored)
- remove `cryptography` from `requirements.in` (because it doesn't actually have to specified there once it's updated in `requirements.txt`)
- document usage in `developer.md`

Update pip-tools, remove versions from req.in, explain usage

---

perma_web/api/tests/utils.py
perma_web/fabfile/dev.py

Doing this in fabric for 2 reasons:
1) it covers the whole test suite, including code that is imported/invoked outside of any particular test
2) you can see the tmp file created, used, and deleted all in one spot, instead of across multiple files (for instance, if the tmp dir was created in settings_testing
But, I'm totally open to other potential solutions. This was just the only thing I could think of.
See https://github.com/harvard-lil/perma/issues/2139

Use a tmp dir for MEDIA_ROOT when running tests; clean up afterwards.

---

perma_web/api/urls.py

With DEBUG=False, try
```
curl -H 'Content-Type: application/json' -X POST -d '{"url": "asdf:[/p]zxcv.com"}' http://api.perma.dev:8000/v1/archives/?api_key=8e1c8dfd8d7f776715ed9074ed0186b6c27bf63d
```
You'll see the expected error (invalid IPv6), plus some middleware-related errors.
The middleware errors are because the api 500 handler needed a return :-)
Added very short text too, for dev happiness using curl.

Avoid middleware errors when API error handler invoked

---

perma_web/fabfile/dev.py
perma_web/requirements.in
perma_web/requirements.txt
perma_web/setup.cfg

There's a memory problem with python unittest in 2.7. Short version of the story: data initialized during self.setUp isn't freed at the end of the test. This behavior is changed in 3.4. See https://chrisbailey.blogs.ilrt.org/2013/05/19/pythons-leaky-testcase-aka-hidden-gotchas-using-self/ and https://bugs.python.org/issue11798
As a result, as our test suite has grown, we've needed more and more memory to run the tests. We've gotten to the point where over 2GB of RAM is required.... more than @anastasia and @rebeccacremona have available in our dev boxes. So, when running the complete suite of tests locally, we start getting failures midway, of the form `OSError: [Errno 12] Cannot allocate memory` or `raise WebDriverException("Unable to start phantomjs with ghostdriver: %s" % e) …

Run tests with pytest by default.

---

perma_web/perma/tasks.py

Right now, writing CDX lines in production involves calling out to S3 and reading back the warc. This can fail for unimportant reasons. For instance, it appears to at least occasionally be true that, in an entirely successfully capture and save process, we sometimes reach the CDX line creating code before S3 has a warc ready for us to read. (More investigation required: is the save asynchronous, and we should be waiting to join a thread? etc.) 
Since CDXlines are created on playback anyway, creating them here is nonessential (though required presently for tests to pass).
Let's ignore errors for now, and consider removing these lines entirely in the future.

Don't die if we can't write CDX lines here.

---

perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/password_change_embedded_form.html
perma_web/perma/templates/registration/password_change_form.html
perma_web/perma/templates/registration/password_reset_confirm.html
perma_web/perma/templates/registration/password_update_form.html
perma_web/perma/templates/registration/set_password.html
perma_web/perma/tests/test_views_auth.py
perma_web/perma/tests/test_views_user_management.py
perma_web/perma/urls.py
perma_web/perma/utils.py
perma_web/perma/views/user_management.py
perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

For PCI compliance:
```
(a) Are user password parameters configured to
require passwords/passphrases meet the
following?
 A minimum password length of at least
seven characters
 Contain both numeric and alphabetic
characters
Alternatively, the passwords/passphrases must have
complexity and strength at least equivalent to the
parameters specified above.
```
This PR does two things:
1) immediately imposes stricter password policies for new passwords (which covers new users and any current users who reset or change their passwords)
2) adds a configuration variable VALIDATE_ALL_PASSWORDS, False by default, which if True, checks a user's password against the current validation rules when they log in. If it doesn't meet the requirements, they are forced to update it.
To force all users to …

Password validation

---

perma_web/perma/templates/base-responsive.html
perma_web/perma/templates/return_policy.html
perma_web/perma/urls.py
perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

Adds a link to the footer.
This makes the footer so wordy that I had to adjust the footer styling: we toggle to the blue mobile-style footer at a larger screen size now. I think it's fine; happy to readdress if anybody hates it.

Add return policy page

---

perma_web/perma/models.py

See issue 2162.
With this change, we can capture http://www.berkshireeagle.com/stories/cyberattack-spreads-in-asia,507471 using PhantomJS (still a playback problem, related to cookies, but that's a project for another day). 
Follows up on https://github.com/harvard-lil/perma/commit/1e1b188675313b8c35c233b13b8889a205e723cc, which adds support for capturing urls like http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل using PhantomJS and Warcprox.

Percent encode URLs using requests

---

perma_web/perma/models.py

Fixes https://github.com/harvard-lil/perma/issues/2183

Explictly encode with utf-8 to prevent implicit encoding with ascii.

---

perma_web/perma/templates/user_management/settings-profile.html
perma_web/perma/templates/user_management/settings-subscription-cancel-confirm.html
perma_web/perma/templates/user_management/settings-tools.html

In response to https://github.com/harvard-lil/perma/issues/2114
That block was evidently removed and replaced with new navigation here:
https://github.com/harvard-lil/perma/commit/4f032ac620cddf88c3f05fbc0e38e3f3d298e1a8#diff-138fcbc2c4c4d493b502bd6e38eb70abL5
https://github.com/harvard-lil/perma/commit/4f032ac620cddf88c3f05fbc0e38e3f3d298e1a8#diff-79c8a495f54d1f71c087d2036720a74bR8

Remove unused block.

---

perma_web/warc_server/pywb_config.py

Provide full request and traceback info to the logger.error call in pywb_config, so we get reasonable error emails from Django's email-admins handler.

Fix error emails from pywb

---

docker-compose.yml
perma_web/.dockerignore
perma_web/Dockerfile
perma_web/fabfile/dev.py
perma_web/functional_tests/tests.py
perma_web/perma/settings/deployments/settings_common.py

(I rebased https://github.com/harvard-lil/perma/pull/2203, so can't reopen. This adds a commit with Jack's suggested tweak.)
Original PR notes follow.
___
This PR adds the tools for an optional Docker-based development environment. 
It can exist side-by-side with the current Vagrant development environment. The `node_modules` directory utilized by Vagrant will be unaffected, and different databases will be used by Vagrant and by Docker. But, for developer convenience during the transition, both Vagrant and Docker will write warcs and static files to your local `services/django/` directory, and both will log to  your local `services/logs` directory.
Add these aliases to your .bash_profile to seriously cut down on keystrokes:
```
alias dfab="docker-compose exec web fab"
alias …
```

Docker dev environment

---

docker-compose.yml
perma_web/.dockerignore
perma_web/Dockerfile
perma_web/perma/settings/deployments/settings_common.py

Add RabbitMQ so celery tasks can be run by workers.
Add Redis, so you can experiment with prod-like caching, and as prep for future integration with pywb/WebRecorder.
To use, comment in the desired services in docker-compose.yml, and comment in the necessary named volumes.
RabbitMQ requires no additional configuration, though it will not be used unless Django settings have RUN_TASKS_ASYNC = True. (=True by default, but usually toggled to False by devs in settings.py)
To configure Redis, add the below to settings.py (same as settings_prod, except the location is at host 'redis' instead of 'localhost')
```
CACHES = {
"default": {
"BACKEND": "django_redis.cache.RedisCache",
"LOCATION": "redis://redis:6379/0",
"OPTIONS": {
"CLIENT_CLASS": "django_redis.client.DefaultClient", …
```

Docker services

---

perma_web/Dockerfile

As with travis build.
Expect a slow build, the next time you build the docker image: this unfortunately invalidates all our build layers lol.

Build from our phantomjs to avoid bitbucket flakiness

---

perma_web/perma/models.py
perma_web/perma/tasks.py

Part 1 of fix for https://github.com/harvard-lil/perma/issues/2216
(I should probably also lowercase all existing content_type fields. TBD.)

Use lowercased content types everywhere.

---

perma_web/perma/models.py
perma_web/perma/tasks.py

Makes "Yowza" stick as title:
```
curl -H 'Content-Type: application/json' -X POST -d '{"url": "http://example.com", "title": "Yowza"}' http://api.perma.test:8000/v1/archives/?api_key=<api key>
```

Take title from api

---

perma_web/functional_tests/tests.py
perma_web/static/bundles/create.js
perma_web/static/bundles/global.js
perma_web/static/js/folder-tree.module.js
perma_web/static/js/helpers/general.helpers.js

Addresses https://github.com/harvard-lil/perma/issues/681.
Folder specified in the URL takes precedence over that in local storage and causes local storage to update.
I decided not to use the fragment, because I think that might have unexpected effects: browsers will attempt to scroll to and set focus to an element with id equal to the fragment. If no such element exists, keyboard focus is usually dropped and set to the top-level html element, and the screen scrolls back to the top. Altering the query string should avoid those problems.

Link straight to folders on manage/create page. 

---

perma_web/api/serializers.py
perma_web/api/tests/test_link_resource.py
perma_web/api/urls.py
perma_web/api/views.py
perma_web/perma/templates/docs/developer/index.html
perma_web/perma/utils.py
perma_web/perma/views/common.py

https://github.com/harvard-lil/perma/issues/1642
Public archives can be downloaded at `/api/v1/public/archives/:guid/download` without an api_key.
All archives can be downloaded by qualified users (admins, private link owners) at `/v1/archives/:guid/download?api_key=<appropriate api key>` .
The URL used to download warcs via the GUI, `/:guid/?type=warc_download`, still works exactly like it did before: public archives may be downloaded by anyone there, and private archives may be downloaded by qualified users if they have an authenticated session (i.e. are logged in, via the log in form). This URL (still) cannot be authenticated using an API key.

Api routes for downloading warcs

---

perma_web/perma/templates/user_management/manage_registrars.html
perma_web/perma/views/user_management.py

This means we'll hit the the database once per registrar displayed on the page, but since this view is paginated, and since this is an admin-only view, I'm not worried. 
(This well might be more efficient than annotating with the counts in the first place, since that had to be done for ALL registrars, not just the ones on the desired page.)

Count orgs on the python side to avoid counting deleted orgs.

---

perma_web/api/serializers.py
perma_web/api/utils.py

This fixes a significant bug @abziegler noticed on stage: 500 on requests that need warc_download_url that come in to api.perma.cc rather than perma.cc/api
Our tests all use /api/v1/<route> to work around a similar issue: https://github.com/harvard-lil/perma/blob/develop/perma_web/api/tests/utils.py#L110
We should address that TODO soon: optimally, we should run all tests at both urls, but with the spped of the current tests, that's not feasible.

Handle requests to both api and api mirror.

---

perma_web/perma/templates/archive/archive-error.html
perma_web/warc_server/pywb_config.py

falling back on today's date when wbrequest's wb_url object doesn't include timestamp field

sending users to mementoweb's Time Travel instead of Internet Archive

---

perma_web/perma/templates/base-responsive.html
perma_web/perma/templates/includes/upper_right_menu.html
perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

Addresses https://github.com/harvard-lil/perma/issues/2242.
I'm not attached to these particular names/labels or this solution at all.
I went with "main nav" and "main dropdown" because I saw that the docs consistently refer to that dropdown as the "main dropdown". I'm hoping that labeling it as such, and nesting it inside something called "main  nav" would make it easier to find and identify, if you didn't already know what it was.
I broke the footer nav into "Learn More" and "Terms and Conditions" primarily because of the existing markup, which makes these two lists, and because there are so many items there, I feel like a little structure is helpful: either two separate labeled navs, or some headings. I went with two labeled navs so that it is potentially easier to jump straight to the …

Main site navigation accessibility

---

perma_web/perma/templates/docs/accounts.html
perma_web/perma/templates/docs/docs_menu.html
perma_web/perma/templates/docs/faq.html
perma_web/perma/templates/docs/index.html
perma_web/perma/templates/docs/libraries.html
perma_web/perma/templates/docs/perma-link-creation.html
perma_web/static/bundles/global-styles.css
perma_web/static/css/style-responsive.scss

Fixes https://github.com/harvard-lil/perma/issues/2248; partial fix for https://github.com/harvard-lil/perma/issues/2247
There is a bit of redundancy here between aria-labels and headings, but I think that's both okay, and inevitable: I don't want the subheadings in the lists to be `<h2>`.

Guide navigation accessibility

---

perma_web/perma/templates/about.html
perma_web/perma/templates/docs/developer/toc.html
perma_web/perma/templates/manage-layout.html
perma_web/perma/templates/privacy_policy.html
perma_web/perma/templates/settings-layout.html
perma_web/perma/templates/terms_of_service.html

Addresses remainder of https://github.com/harvard-lil/perma/issues/2247 and https://github.com/harvard-lil/perma/issues/2249
The solution for the API docs might be overly verbose, but I can't think of anything more succinct. This is a rather uncommon design, in my admittedly limited experience: I'm not sure there's a great solution. If we felt like it, we could consider breaking this into multiple pages, or making a single, accordion-style menu that positions itself via css.... but that sounds like much too much work. This verbose technique is probably better bang for our buck.

Accessible Tables of Contents

---

perma_web/perma/templates/includes/upper_right_menu.html

In https://github.com/harvard-lil/perma/pull/2271, I had improper nesting for all users except admins and registrar users. 
This restores the correct appearance.
Note to self: always visually test all kinds of users.... not just with screen reader!

Fix main dropdown appearance

---

perma_web/perma/templates/archive/dark-archive.html
perma_web/perma/templates/archive/single-link.html
perma_web/static/bundles/single-link-styles.css
perma_web/static/css/style-responsive-archive.scss

Addresses https://github.com/harvard-lil/perma/issues/2264; also adds more specific link for users who view the link when not logged in.

Link straight to docs about private perma links

---

perma_web/requirements.in
perma_web/requirements.txt

This fixes a problem obscured in one case on Heroku by the uninvited presence of boto 2.42.0. (Probably see https://github.com/heroku/heroku-buildpack-python/issues/379.) Kombu requires boto, not boto3, to talk to SQS.

Install boto in order for Kombu to use SQS

---

perma_web/perma/templatetags/current_query_string.py

This allows us to search for users/registrars/orgs with umlauts, etc. in their names on the /manage pages.

Don't implicitly cast values to ascii

---

perma_web/static/bundles/create.js
perma_web/static/js/links-list.module.js

Ensures infinite scroll is triggered when scrolling to the bottom of the links list, regardless of various interfering variables.

Tie waypoint to column to decouple from zoom/viewport/window.

---

perma_web/perma/urls.py

Fixes https://github.com/harvard-lil/perma/issues/2309
Reproduced locally by changing a link's GUID in the shell.

Perma Links come in many sizes!

---

perma_web/api/urls.py

I noticed this when setting up the new UptimeRobot monitors: the "root" api view is only available with a trailing slash, due to the way we've structured the "include."
I don't think it's worth rewriting every single api route to explicitly include an initial slash so that we can avoid this one quirk.  But if others disagree, I'm happy to.

Document atypical route

---

perma_web/static/bundles/single-link-styles.css
perma_web/static/css/style-responsive-archive.scss

I didn't realize the 'include' for the main dropdown was reused on the single-link page, and broke it in https://github.com/harvard-lil/perma/pull/2271
This restores the appearance. It makes no attempt to fix the accessibility of that page, or apply other changes I made to the main nav in #2271. That's a project for another day!

Restore appearance of single-link dropdown

---

perma_web/api/urls.py
perma_web/api/utils.py
perma_web/api/views.py
perma_web/static/bundles/create.js
perma_web/static/js/link-batch.module.js

Pass urls to LinkBatch creation API route, instead of having to first create a batch and then add individual links to that batch via the standard archive creation api route. This:
-  streamlines the batch creation process and simplifies the js
-  prevents the addition of links to batches at arbitrary times
-  eliminates the need to add code to make sure users aren't attempting to add links to someone else's batch (code that was not present to this point: you could simply guess a batch id and if you were right, you could add links to that batch)
But the code is unusual. It is an adaptation of one of the experiments from this January (https://github.com/harvard-lil/perma/compare/develop...rebeccacremona:bulk-experimenting), where I created a route for sending Perma a "batch" of arbitrary …

Pass urls to LinkBatch creation API route

---

perma_web/api/views.py

(e.g. normal Perma Link creation).

Whoops. Handle cases where request.batch is not present.

---

perma_web/perma/templates/archive/includes/link_batch_modal.html
perma_web/perma/templates/user_management/create-link.html
perma_web/static/bundles/create.js
perma_web/static/js/hbs/batch-links.handlebars
perma_web/static/js/link-batch.module.js

Have I mentioned that this is a complex UI?
1) With all these modals popping up and down, we have to make sure keyboard focus gets set back to the element that opened them, on close.
2) When the form is submitted, the submit button is zapped, so we set focus to a hidden "Loading" message wrapped with the spinner. When the batch has been created, the spinner gets zapped, so we have to pass focus off again....
3) But there's still a fair amount of action happening: the list of links gets updated every 2 seconds until every link in the batch is complete. Handlebars is swapping in and out elements like mad: this is a minefield for keyboard/screen reader focus until the batch is complete. So, we rope it off for safety: until the batch is complete: all elements are made impossible to tab to, …

Handle keyboard focus; report batch progress.

---

perma_web/static/bundles/create.js
perma_web/static/js/link-batch.module.js

Instead of submitting them and generating invalid capture jobs with the message "URL is a required field".

Filter out empty lines

---

perma_web/api/utils.py
perma_web/api/views.py
perma_web/perma/settings/deployments/settings_dev.py
perma_web/perma/settings/deployments/settings_travis.py

This should solve the `Exception Value: Invalid HTTP_HOST header: 'testserver'.` we're seeing on stage when creating link batches as a result of my implementation of `dispatch_multiple_requests`.
The batch and all the links in the batch are being created correctly, but when serializing the individual links, DRF is trying to produce the absolute URL to download the WARC, and it can't, because the RequestFactory is setting the SERVER_NAME to `testserver`, which is not in ALLOWED_HOSTS:
```
def _get_raw_host(self):
"""
Return the HTTP host using the environment or request headers. Skip
allowed hosts protection, so may return an insecure host.
"""
if settings.USE_X_FORWARDED_HOST and (
'HTTP_X_FORWARDED_HOST' in self.META):
host = self.META['HTTP_X_FORWARDED_HOST']
elif 'HTTP_HOST' in …
```

Pass along the HTTP_HOST so that DRF can produce absolute URLs.

---

perma_web/api/serializers.py
perma_web/static/bundles/create.js
perma_web/static/js/hbs/batch-links.handlebars

In the regular link list, deleted links do not appear. That's appropriate, because the link list shows the "contents" of a folder: you would not expect deleted things to remain.
The batch modal is different: if you subsequently delete all the links in a batch, you wouldn't expect to see an empty modal!
This PR adds deletion status to the CaptureJob and Link api results, and adds some styling etc. to the batch modal.

Deleted links, batch interface and API

---

perma_web/perma/templates/archive/includes/link_batch_modal.html
perma_web/static/bundles/create.js
perma_web/static/js/helpers/folder-selector.helper.js
perma_web/static/js/link-batch.module.js

1) Make it clear when no folder is selected by including a default, blank option in the dropdown, labeled, "Please select a folder".
2) Disable the button for creating a batch unless a folder is selected.
3) When a user selects a folder, announce that change so that the FolderTree and LinkList modules update the UI accordingly and everything works as expected. (Since links are being added to the link list in the background, etc., this is actually necessary, even if you can't see what's happening behind the modal.)

Batch folder selection dropdown

---

perma_web/perma/models.py
perma_web/perma/tasks.py
perma_web/perma/tests/test_capture_job.py

- Make sure we set CaptureJob.message when setting status='failed', in the same format that we sometimes do now (`'{"errors":["reason"]}'`).
- Whenever `run_next_capture` is run (which should be at least once a minute due to celerybeat), mark any jobs as failed that have been in_progress longer than the celery hard timeout.
Note that this will update all the jobs we currently have on prod that managed to stick around as in_progress in the past. I think it's safe to say we're not planning to do anything with those at this point anyway. But it will also set `capture_job.link.tags.add('hard-timeout-failure')` on those jobs, so we could find them if necessary.

CaptureJob failure messages and cleanup of old jobs

---

perma_web/api/serializers.py
perma_web/api/views.py
perma_web/static/bundles/create.js
perma_web/static/js/folder-tree.module.js
perma_web/static/js/hbs/link-batch-history.handlebars
perma_web/static/js/link-batch.module.js

The whole UI updates to display the target folder of the batch. Since folders are lazy-loaded, that target folder may not yet have been retrieved by the API. (This will be the case every time a batch is associated with a child folder not-yet-viewed in the current browser tab). 
This PR reloads the folder tree when you open the modal for a batch in your batch history.
closes https://github.com/harvard-lil/perma/issues/2361

Reload folder tree when opening batch

---

perma_web/api/views.py
perma_web/static/bundles/create.js
perma_web/static/js/link-batch.module.js

Otherwise, batch links will see too big of a delay.

Capture requests initiated by the modal are "human" for timing purposes.

---

perma_web/api/views.py

note: it turns out Excel doesn't default to utf-8... you have to select it in the import wizard! weird.

utf-8 encode all data in csv rows

---

perma_web/perma/templates/archive/archive-error.html

Closes https://github.com/harvard-lil/perma/issues/1946.
This particular error page is displayed by our custom pywb error handler during playback. It doesn't have access to a Link object, only a url and an error message: not enough to recover the GUID being played back, and so not enough to determine whether a screenshot is available. So, I'm just removing the whole reference to the screenshot.

Remove reference to screenshot view.

---

perma_web/warc_server/pywb_config.py

If pywb is expecting latin-1, give it latin-1.
This seems to allow correct playback of the three urls....
- http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل
- https://www.facebook.com/concernedontariodoctors/photos/a.857920334342074.1073741832.720893411378101/1331816100285826/?type=3&theater
- https://www.facebook.com/pkrant/posts/2002889319755215
....all at the same time.
This makes a bit more sense than the last attempt. But, I still want to confer w/ the WR team about how pywb handles encoding.

Attempt 2 to fix https://github.com/harvard-lil/perma/issues/2416

---

.travis.yml
perma_web/fabfile/dev.py
perma_web/perma/settings/deployments/settings_prod.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/settings/deployments/settings_travis.py
perma_web/warc_server/pywb_config.py

This also tidies our testing settings.

Load warcs from default storage to avoid permissions complications.

---

perma_web/warc_server/pywb_config.py

```
Non-ASCII values in the WSGI environ are arbitrarily decoded with
```
Django solves this using:
- https://github.com/django/django/blob/98e8c0293b96de7dea74817476847c363d9c2496/django/core/handlers/wsgi.py#L155
- https://github.com/django/django/blob/98e8c0293b96de7dea74817476847c363d9c2496/django/utils/encoding.py#L225
I made an effort to emulate that in a previous version of this patch, when I noticed http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل wasn't playing back. But, my patch was incomplete and didn't work for timemap queries like `curl 'http://perma-archives.test:8000/warc/timemap/*/http://example.com/%F6'`.
So, just use Django's own util function.

Use django's utils for getting url from wsgi env.

---

perma_web/perma/admin.py

- display url in list view
- don't include a dropdown of every perma user in the single CaptureJob view, for much faster page loading

Tweak CaptureJob admin view

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/utils/post_processing.py
perma_web/perma/views/link_management.py

Closes #2448. Counting celery workers is slow, so we're moving it to settings.utils.post_processing; the database query and computation are fast.

Move worker count to settings.utils.post_processing

---

perma_web/fabfile/dev.py
perma_web/perma/email.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tasks.py
perma_web/perma/tests/test_tasks.py

We send ourselves some administrative emails. Most of those should only go to whoever is currently in settings.ADMINS. Occasionally, we might want to email the main Perma email address and open a ticket. This PR adds a utility function for sending ourselves mail and switches existing code to use it, always with the default (=no ticket).
Perma Payments is going to need the same change.

Better handing of email we send to ourselves

---

perma_web/perma/templates/contact.html
perma_web/perma/templates/docs/accounts.html
perma_web/perma/templates/email/new_user.txt
perma_web/perma/templates/registration/sign-up.html
perma_web/perma/templates/user_management/create-link.html
perma_web/perma/views/common.py
perma_web/perma/views/user_management.py

We did not design our infrastructure such that individual users can subscribe to unlimited accounts, but we can reuse the Registrar -> Org -> user setup to make do.
This PR offers "premium,  unlimited" accounts to individual users during sign-up, on their /manage/create page, and in the docs. It sends them to a souped-up version of our contact form to "upgrade".
I put in some copy; I don't imagine it's what we'll want to deploy.
This PR does not address the second half of this project: adapting the code to make the Registrar -> Org setup smoother (and harder to misuse), when it is used to shoehorn individual users into our paid account setup.

Individual users may request paid accounts

---

perma_web/perma/templates/email/admin/deletion_request.txt
perma_web/perma/templates/user_management/settings-profile.html
perma_web/perma/tests/test_views_user_management.py
perma_web/perma/urls.py
perma_web/perma/views/user_management.py

Logged in users can request account deletion via their profile page:
After pressing the button, in the Django admin:
User then sees:
We also get an email, like when a special user signs up. It should create a ticket in FreshDesk.

Throw together a mechanism for requesting account deletion.

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tasks.py

Some warcprox threads aren't stopping promptly, despite the patch, and I'm not sure why at this moment. I'd like to investigate more, but I think we should try to make Perma robust even if I never figure out all the edge cases.
This PR changes the `warcprox_controller.proxy.pool.shutdown` call to non-blocking, which should prevent the capture process from hanging and eventually timing out and failing. 
It also introduces a short `SHUTDOWN_GRACE_PERIOD` to allow warcprox a little time to deal with threads stopped via https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L956. During quick, normal captures, there are often 2 active threads at this point: if any more are active, we'll wait up to `SHUTDOWN_GRACE_PERIOD` for them to finish up.
This adds up to 5s to the …

Give warcprox threads a chance to stop

---

perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tasks.py

This should get the test speed back to about 9 min: if it doesn't, there's a problem.
Note this fixes a typo from my last PR: I never set `SHUTDOWN_GRACE_PERIOD = settings.SHUTDOWN_GRACE_PERIOD` in tasks.py, so the testing override had no effect. But, testing on my fork suggests an override for testing is not necessary.

Don't wait unless its MitmProxyHandler threads.

---

perma_web/api/tests/test_link_resource.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py
perma_web/perma/tests/assets/target_capture_files/perma-noarchive.html

This PR adds a setting, PRIVATE_LINKS_IF_GENERIC_NOARCHIVE.
Perma's current behavior is True: though we only respect robots.txt directives if Perma is mentioned by name, we respect meta tags and x-robots headers directed at generic "robots" (http://noarchive.net/).
This PR keeps the default of `True`; we can toggle in settings_common when we are ready, or override when ready by deployment-specific settings.py

Noarchive behavior

---

perma_web/Pipfile.lock
services/heroku/runtime.txt

- increments runtime because... why not
- manually removes "null" marker that pip 9 + pipenv can't handle 😢

Heroku build

---

perma_web/fabfile/dev.py

(There are so many Django 2.0 deprecation warnings that the build is failing)

Ignore warnings on Travis for now.

---

perma_web/perma/templates/contact.html
perma_web/perma/templates/email/new_user.txt
perma_web/perma/templates/registration/sign-up.html
perma_web/perma/tests/test_models.py
perma_web/perma/views/common.py
perma_web/perma/views/user_management.py

There should be no conflicts with https://github.com/harvard-lil/perma/pull/2519/files, which doesn't alter the actual forms.
Currently, when an organization clicks the links to request more information about a paid organizational account, they see the below:
This PR switches it to:

No "upgrades" for individuals on contact form or sign up form

---

perma_web/perma/templates/about.html

- tidies HTML
- adds some styling (lists have no bullets in general in our styles; seems unnecessary to add a whole class just for this one list)
before:
after:

List on "about" page

---

docker-compose.yml
perma_web/fabfile/dev.py
perma_web/perma/settings/deployments/settings_common.py
services/docker/webrecorder/nginx/502.html
services/docker/webrecorder/nginx/Dockerfile
services/docker/webrecorder/nginx/nginx.conf
services/docker/webrecorder/nginx/webrec.conf
services/docker/webrecorder/wr-custom.yaml
services/docker/webrecorder/wr.env

This is a first pass at running WR locally using our pre-built Docker image. 
Includes an alternate command for `web` in `docker-compose.yml`, if you want Perma to start up automatically when you run `docker-compose up`
If doing simultaneous WR and Perma development, see the instructions at the bottom of `docker-compose.yml` to adjust the network.
Includes two utility functions for clearing WR-related data from Perma's session store, useful when debugging/ restarting services.

Some utils for running Perma with WR

---

perma_web/perma/admin.py
perma_web/perma/templates/admin/perma/linkuser/change_form.html

I had to remove the feature that used to allow admins to inspect a user's links: links were displayed as an inline on the LinkUser admin page. That made the form illegal to submit, for users with medium-to-large numbers of links: every link added two inputs to the form, all of which POSTed! Altering that behavior of the admin was proving gruesome at best, impossible at worst. So, I removed it.
This PR attempts to provide equivalent functionality by:
- making it possible filter the Link admin by searching for an email address
- putting a link to that filtered view at the bottom of the LinkUser admin page
And while I was in there, I fixed the Folder admin page so it should load in prod now without difficulty.

Let admins review a user's links

---

.travis.yml
docker-compose.yml
perma_web/functional_tests/tests.py
perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tests/test_urls.py
perma_web/perma/tests/test_views_common.py
perma_web/perma/utils.py
perma_web/perma/views/common.py
perma_web/perma/views/user_management.py
services/docker/webrecorder/uploadcontroller.py
services/docker/webrecorder/usercontroller.py
services/docker/webrecorder/wr.env

This PR fixes a number of issues that were uncovered by running tests locally with `ENABLE_WR_PLACKBACK=True`, and adds infrastructure for running functional tests using headless Chrome in a Docker container whose image is managed by SeleniumHQ.
It does not change how tests run by default: `ENABLE_WR_PLAYBACK` and `REMOTE_SELENIUM` are both False.
To-dos and remarks:
- It does not appear that Webrecorder playback works in PhantomJS; TBD.
- Perma's JS error reporting does not appear to work with the dockerized Chrome; TBD
- This includes two workarounds for WR auth difficulties; TBD with WR team.
- This does not include a mechanism for easily switching between WR "dev" and "testing" settings (toggle comments, restart the containers in between)
- Next: Travis config for running with …

Tests w/ WR playback (local only)

---

.travis.yml
docker-compose-travis.yml
docker-compose.yml
perma_web/fabfile/dev.py
perma_web/functional_tests/tests.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/tests/test_views_common.py
services/docker/webrecorder/nginx/nginx.conf
services/docker/webrecorder/wr.env

- upgraded to Trusty to get a recent-enough Docker/Docker-Compose
- upgrading to Trusty required losing the option to run functional tests w/ the Travis pre-installed Firefox; our Selenium is too old to handle the slightly-more-modern Firefox that comes with Trusty. To run tests with Firefox, we should get the dockerized Selenium/Firefox working.
This PR does *not* toggle on Selenium/Chrome or Webrecorder playbacks. You can test with Selenium/Chrome + pywb playback, if you want, but Webrecorder playback cannot be tested with PhantomJS; best I can tell, it requires a more modern browser.
If you want Travis to test with Webrecorder playbacks, toggle `REMOTE_SELENIUM` and `ENABLE_WR_PLAYBACK` from `False` to `True` in `settings_testing.py` (....necessary so that the related settings also get …

Optionally run tests with Selenium/Chrome and Webrecorder on Travis

---

.gitignore
developer.md
docker-compose.yml
perma_web/Pipfile
perma_web/Pipfile.lock
perma_web/fabfile/dev.py
perma_web/static/bundles/create.js
perma_web/static/js/hbs/link.handlebars

This defaults to `runserver` unless you're using SSL; I can add the option to use `runserver_plus` without SSL if it seems like a good idea.

SSL in docker

---

docker-compose-travis.yml
docker-compose.yml
services/docker/webrecorder/docker-entrypoint.sh

Before, we were doing this in the image:
- https://github.com/webrecorder/webrecorder/commit/81eebd5f5c00ee0078a20850780e335fd8290b14
- https://github.com/webrecorder/webrecorder/commit/c7f247f12a2209bfd12285bf79849841098b1d11
That worked well locally, but didn't seem to work with the NFS volume: permissions/contents were getting overwritten, rather than being populated from the container, regardless of how `nocopy` was set.
This uses a different approach: every time you spin up a `recorder` container, it will ensure it has access to the directories it needs.
There's some fanciness involved, because the image runs with `USER archivist` by default, which of course cannot create directories in `/`, etc. So, we specify `user: root` in our `docker-compose.yml` and use shell fanciness in …

Set up directories for the recorder container via entrypoint.

---

perma_web/api/views.py
perma_web/perma/utils.py

We keep track in the user's session whether a particular WARC has already been uploaded to webrecorder on behalf of that user, to save some time. If a user wants to replace a capture gone wrong, we need to clear that out, so that the new warc is uploaded. Easiest way is to just clear the whole session.

Replacements and WR

---

perma_web/perma/settings/deployments/settings_testing.py
perma_web/perma/settings/utils/post_processing.py
perma_web/perma/tasks.py
perma_web/perma/tests/test_tasks.py

Try it out locally by setting `RUN_TASKS_ASYNC = False` and `CELERYBEAT_JOB_NAMES = [ 'verify_webrecorder_api_available']` and re-running `fab run`.
Enable on a Perma server by appending this new celerybeat job to the existing setting array `CELERYBEAT_JOB_NAMES`

Monitor WR api for availability.

---

perma_web/perma/utils.py

404s are expected here: if the WR session has timed out, WR will delete the temp user. Perma will still have a cookie stored in the user's session (Django has no mechanism for automatically expiring individual keys stored in sessions, only for expiring the whole session). So, Perma will send the DELETE request just to make sure. Don't count that as an error, unless we're doing something fancy; we can call with `error_if_wr_user_not_found=True` if we need to for some reason.

Less aggressive handling of 404s during WR temp user deletion attempts.

---

docker-compose-travis.yml
docker-compose.yml
services/docker/webrecorder/contentcontroller.py

This patches Webrecorder to add a mechanism for blocking the playback of blacklisted urls, similar to https://github.com/harvard-lil/perma/pull/2426/files.
We should add `contentcontroller.py` to the list of files we watch in the WR repo, after this is merged.
Let's discuss the best way to set the env var `REFUSE_PLAYBACK` so that we don't expose the list in the repo. Probably, the easiest/best way is to interpolate it into `wr.env` via Salt, along with other confidential config. Probably should NOT mimic the dev setup I'm using here, where docker-compose sets an env var in the container by interpolating the value of `REFUSE_PLAYBACK` in my shell (my bash shell on my mac). 
`REFUSE_PLAYBACK` should be a comma separated list, like …

Hack to refuse playback of particular urls or domains.

---

perma_web/perma/email.py
perma_web/perma/templates/404.html
perma_web/perma/tests/test_views_common.py

1) don't html-encode them in emails
2) url-encode them before printing into the `href`  of the email-sending link on the 404 page

Html entities

---

docker-compose.yml
services/docker/webrecorder/main.py
services/docker/webrecorder/tempchecker.py

This PR gives us the option of applying the changes in https://github.com/webrecorder/webrecorder/pull/716 before they land upstream.
Closes https://github.com/harvard-lil/perma/issues/2604.
If merged: tempchecker logs can be quieted by adding a new environment variable on the WR minions. We can set `WR_DEBUG=False` in `wr.env` if that's easiest, or add
```
environment:
- WR_DEBUG=False
```
to the recorder service's stanza of `docker-compose.yml` if preferable, etc.

WR tempchecker logging

---

services/docker/webrecorder/app_main.py

The CDX indexer doesn't expect spaces there. Warcio is responsible for parsing the warc and reading the headers. I found this function that performs a bit of validation on WARC-Target-URI https://github.com/webrecorder/warcio/blob/c64c4394805e13256695f51af072c95389397ee9/warcio/recordloader.py#L217
So, for now, I added a little more validation.....
To be discussed with the Webrecorder team.
Should address at least some of https://github.com/harvard-lil/perma/issues/2605

Flailing attempt to deal with WARC-Target-URI that contain spaces.

---

services/docker/webrecorder/app_main.py

Not sure this is right either, but it's definitely more correct than stripping.

Replace with url-encoded space; don't strip.

---

docker-compose.yml
services/docker/webrecorder/maincontroller.py
services/docker/webrecorder/wr-custom.yaml

1) expires the cdx of "public" collections more quickly, to prevent our disk from filling up, since we don't need them anyway
2) tries adding values for "extending" sessions, to see if that solves the SETEX bug we're seeing, a bug I do not yet understand
3) attempts to deal with the uninformative error tuples being printed by `app` by logging the request URL that raised the error, and by logging the stack trace, if one is available. Expect the 404 tuples to be replaced by a log line like:
```app_1             | wr.io: 2019-06-07 15:14:29: [WARNING]: 400 (cremona_said_no) raised by http://perma-archives.test:8092/temp-5GWAX6IW/x36b-ynah/20190107155654mp_/http%3A/example.com```
Sorry, involves mounting yet another file into the containers.... I'll start making PRs upstream next week so this …

Three small, unrelated changes

---

docker-compose.yml
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py

An attempt to address https://github.com/harvard-lil/perma/issues/2131 and https://github.com/harvard-lil/perma/issues/2584 without breaking anything else.
We should test thoroughly on stage before deploying, by capturing lots of domains on stage, observing whether the capture attempt was rejected/blocked by the domain, and checking to see if we get the same results on prod. With any luck, we will not find any domains that ACCEPTED the old user-agent, but REJECT the new one.
To close 2584, we will also have to tell their developers about our unique suffix.

Capture User-Agent

---

services/docker/webrecorder/session.py

I'm pretty sure this is it. If we like what we see, with this running, then I can send another PR (here and upstream) that just changes `<` to `<=`.

See if this quashes the SETEX errors.

---

docker-compose.yml
services/docker/webrecorder/app_main.py
services/docker/webrecorder/importer.py
services/docker/webrecorder/recorder_main.py
services/docker/webrecorder/recordloader.py
services/docker/webrecorder/session.py

- records recent PRs to upstream libraries
- adds logging to help flush out the [mime problem](https://github.com/harvard-lil/perma/issues/2602)
Mime errors should now throw traces like this, so we can get the GUID:
```
app_1             | Traceback (most recent call last):
app_1             |   File "./webrecorder/models/importer.py", line 244, in run_upload
app_1             |     self.process_pages(info, page_id_map)
app_1             |   File "./webrecorder/models/importer.py", line 291, in process_pages
app_1             |     pages = self.detect_pages(info['coll'], info['rec'])
app_1             |   File "./webrecorder/models/importer.py", line 460, in detect_pages
app_1             |     and self.is_page(cdxj)):
app_1             |   File "./webrecorder/models/importer.py", line …
```

WR debugging

---

services/docker/webrecorder/recorder_main.py

First pass at solving https://github.com/harvard-lil/perma/issues/2634.
I landed on 32,768 (2**15) by trying powers of two until the exception disappeared.

Cap length of extended querystring when indexing.

---

perma_web/api/urls.py
perma_web/api/views.py
perma_web/static/bundles/create.js
perma_web/static/bundles/global.css
perma_web/static/css/style-responsive.scss
perma_web/static/js/hbs/link-list-header.handlebars
perma_web/static/js/links-list.module.js

Adds two (as-yet-undocumented) API routes for exporting data on Perma Links as a CSV. Why two, you ask? To match https://perma.cc/docs/developer#view-all-archives-of-one-user and https://perma.cc/docs/developer#view-folder-archives.
(The CSV export for Link Batches is also currently undocumented; maybe I should do all the csv stuff in its own section....)
Adds a button to the header of the link list you can press to download info about the current folder's links.

Export links as csv

---

perma_web/perma/templates/archive/iframe.html

If we can't playback a link due to its file format, we offer a link to download: that link was pointed at the old pywb-based URL. This PR uses our feature flag to provide a WR-appropriate URL.

Interstitial needs different url with webrecorder playback.

---

docker-compose.yml
perma_web/Pipfile
perma_web/Pipfile.lock
perma_web/perma/storage_backends.py
perma_web/warc_server/pywb_config.py

This change lets you use Azure blob storage as a file system backend for WARC files.
To use Azure storage, set the following variables in your `settings.py` file as per https://django-storages.readthedocs.io/en/latest/backends/azure.html:
`AZURE_ACCOUNT_NAME = '<azure storage account name>'`
`AZURE_ACCOUNT_KEY = '<azure account private key>'`
`AZURE_CONTAINER = '<azure container you'd like your files to appear in>`'
Credit goes to @jha-manish for the first version of this work.

Azure media storage

---

.travis.yml
docker-compose.yml
perma_web/Dockerfile
perma_web/Pipfile
perma_web/Pipfile.lock
perma_web/api/tests/test_link_validation.py
perma_web/perma/storage_backends.py
services/mysql/conf.d/custom.cnf

Running on Buster instead of Stretch would solve https://github.com/harvard-lil/perma/issues/2696.
This, if merged, would be a no-op for prod, except insofar as some background python packages are upgraded, due to unavoidable bits of the Pipenv process.
Tests are passing locally; there may still be some fussing for the CI tests.... Will address if so.

Proof of concept: running on Buster.

---

perma_web/perma/tests/test_views_common.py
perma_web/perma/views/common.py

Subsequent to messages from the validator. Not positive this fixes, "First Memento in Header not the same as first in TimeMap".... but, since "first memento" and "last memento" weren't being included in the timegate header, we'll see if merely adding them takes care of it.
If it does.... I'm undecided whether I'm going to add that to the header of actual playbacks. I think I'd prefer not to do the extra DB query.... TBD.

Memento tweaks

---

docker-compose.yml
perma_web/perma/views/common.py
services/docker/webrecorder/contentcontroller.py

This PR attempts to hide the playback flakiness we've been experiencing, but have not yet diagnosed. My best guess is that we are seeing failures due to timing and network conditions within our distributed system. I hope to find and make robust the different spots that are susceptible to that sort of problem... but in the meantime, I propose the follow two potential remedies:
- automatically retry playbacks that fail noisy, producing an exception visible in Django, after 1 second
- if Webrecorder looks for a resource in a Perma Link and doesn't find it (404), wait a second and then have it look again... hopefully mitigating these miserable 404s for the main resource that are happening and then getting cached in Cloudflare as per https://github.com/harvard-lil/perma/issues/2633
Both are …

Retry playbacks

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/views/common.py
services/docker/webrecorder/contentcontroller.py

... and lengthen the default WR sleep from 1 to 2, since I still saw some 404s on stage.

Use settings instead of hard-coding sleeps.

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_dev.py
perma_web/perma/settings/deployments/settings_prod.py

Note: if any tier's `settings.py` sets the name of the log file, we need to change the name of the handler from "default" to "file"

Try new-style logging config, ala capstone, with tweaks.

---

docker-compose.yml
perma_web/Pipfile
perma_web/Pipfile.lock
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py

Motivation: we've been on a relatively early beta release of 2.4, (2.4b2), and since then, they've released 2.4b3, 2.4b5, 2.4b6, 2.4.9, 2.4.17. Surely we'd benefit from some of the changes therein, even if we haven't been noticing major problems with capture.
Testing: local experiments look fine, and I plan to give it some more exercise there, but we should plan to test this pretty extensively on stage, with a wide range of URLs, comparing stage to prod if capture quality seems suspect or if capture failures occur.
Merging and deploying: this should be merged after https://github.com/harvard-lil/perma/pull/2718 (the diff will update to not include that commit, subsequent to its merge, methinks), and then tested, and then I think the two should be deployed to prod together, without other …

Upgrade warcprox

---

perma_web/perma/tasks.py

Sometimes, `warcprox` now returns `None` for `content_type` (https://github.com/internetarchive/warcprox/blob/932001c92115c4881a32d8b8f4d05c00a6efdaa7/warcprox/warcproxy.py#L212). Handle that.

Handle content_type=None during capture.

---

perma_web/api/views.py
perma_web/perma/models.py
perma_web/perma/tasks.py
perma_web/perma/utils.py

We have observed that S3 is not always ready to report the size of uploaded warcs, immediately after upload. As a result, some capture jobs are failing unnecessarily. See https://github.com/harvard-lil/perma/issues/2172 for some discussion, and other various discussions of warc_size.
This PR switches our strategy, getting the size of the warc from our local tempfile, rather than inquiring from S3/the storage backend used by default_storage.

Get warc_size from tempfile, not from default storage.

---

perma_web/perma/utils.py

I can't explain why `out.tell()` in the former position is throwing `I/O operation on closed file` on stage but not locally or in CI, but it is! So, try this instead.

Re-order lines, to potentially avoid closed-file error on certain tiers.

---

perma_web/perma/tasks.py

This task was run on Friday, and seems to have handled 60-70% of links, but not all. From watching the Django admin, I gather that the queue is now empty: I don't see any more links being processed.
Before re-running to get the rest of the links, add a logging line.

Add logging to playback status caching task.

---

perma_web/api/tests/test_current_user_resource.py
perma_web/api/tests/test_link_authorization.py
perma_web/api/tests/test_link_resource.py
perma_web/api/views.py
perma_web/fixtures/archive.json
perma_web/perma/models.py
perma_web/perma/templates/archive/single-link.html

With the new error reporting, we're noticing a variety of peculiar errors go by, all from users deleting a Perma Link while its capture is in progress. Even if the user knows in advance that capture will not produce a satisfactory Perma Link (e.g., they know they are capturing a paywalled resource), we don't want to support a workflow that includes deletion mid-capture: it throws too many spanners in the works. This PR disables deletion and replacement while a link's capture job is `in_progress`. Deletion and replacement are still allowed before capture is started, and after it is completed. 
Users who want a workaround can be  given instructions on how to "upload your own".

Disallow deletion while capture is in progress.

---

perma_web/fabfile/dev.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/settings/deployments/settings_prod.py
perma_web/perma/settings/utils/post_processing.py
perma_web/perma/tasks.py
perma_web/perma/templates/user_management/stats.html
perma_web/perma/views/user_management.py

The current Salt config, `CELERY_BEAT_JOB_NAMES.remove('send-links-to-internet-archives')`, will need the final `s` removed.

Put internet archive tasks on their own queue.

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py

This is a one-time task, to populate the warc_size field for links where we missed it, the first time around. See https://github.com/harvard-lil/perma/issues/2617 and https://github.com/harvard-lil/perma/issues/2172; old links also often lack this metadata.
There are 281,874 links to process. Each should take less than a second. I put this on the background queue; TBD if we are okay waiting. I think, yes.

Task to populate warc_size.

---

perma_web/api/views.py

A while ago, I threw in a feature that lets you download a CSV of metadata about links in a given folder:
It's been broken the whole time: it assumed that all links have capture jobs, which is not true. I have long delayed fixing it because I realized correctly populating the `status` field was wicked complicated...... which is no longer true! Now it's easy.
So, I'm finally fixing it.

Fix CSV download of metadata about links

---

perma_web/perma/tasks.py
perma_web/perma/utils.py
perma_web/perma/views/common.py

Somehow or other, before https://github.com/harvard-lil/perma/commit/272b3a79d94a795142940281c9444b45c24a05db, some users were able to submit URLs with control characters in them. 
I can't decide whether we should try to clean this up in the db in some way... 
In the meantime, this strips control chars from two spots that I think are causing problems: the IA upload task, and the memento headers.

Occasional control characters in old Perma Link urls

---

perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/archive/playback-delayed.html
perma_web/perma/views/common.py

A few times a day, we observe a spurious "not found" for a warc during playback, resulting in a 500 Internal Server Error on the Perma side, visible to the user. The first attempt to play back gets a 404 from S3, as does the retry 2 seconds later.... but every time, without fail, when we follow up, the link plays back fine...
Here's my only theory: these are all from newly-created links, and S3 hasn't fully replicated across it's servers yet. From https://aws.amazon.com/premiumsupport/knowledge-center/404-error-nosuchkey-s3/
> Amazon S3 might return the "NoSuchKey" error if the object was recently uploaded. When you upload an object, Amazon S3 replicates your data across multiple servers, so the newly uploaded object might not be found until after the object is completely replicated …

Warc not found

---

perma_web/perma/settings/deployments/settings_common.py

I am investigating how it can be so big (is limiting mechanism broken?), but, we have a 219MB Perma Link created yesterday. The first attempt to play back always fails, due to WR upload timeout. The second (automatic) attempt always works. So, let's increase the WR upload timeout, see if we can avoid the retry, even for our biggest warcs. (Why is upload happening more quickly on the retry?)

Wait longer for WR upload timeout, to account for large warcs.

---

perma_web/perma/middleware.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tests/test_views_auth.py

Since we now use the Django session for playback, even for anonymous users, the presence of the Django session cookie is no longer a good indicator of when or when not Cloudflare should use its cache.
This PR sets a new cookie for logged-in users, which I believe will restore the intended caching, coupled with a new page rule. 
Caveat: in Firefox and Chrome, I can see that `response.delete_cookie(settings.CACHE_BYPASS_COOKIE_NAME)` indeed entirely removes the cookie. With the test client, I can see that instead, the value is set to `''`, empty string. So, in real life, this might not work for all browsers... but I think it's as close as we are going to get. Worst case scenario is not very bad: the Cloudflare cache may continue to be bypassed for users who have manually logged out, after …

Set a cookie to toggle Cloudflare caching.

---

perma_web/perma/settings/deployments/settings_common.py

https://github.com/harvard-lil/perma/pull/2761 appears to be working; this happens noticeably less frequently. But, it's still happening occasionally. Let's see if another 2 seconds does the job.

See if two more seconds is enough for remaining timeouts.

---

perma_web/perma/email.py
perma_web/perma/wsgi.py

This PR https://github.com/harvard-lil/perma/pull/2765 seems to be working well, for emails sent via our `retrying_send` method. 
This PR switches to a global monkeypatch, to cover every email sent by Django, for instance, `/password/reset`, which aren't sending manually.

Patch Django's email function globally, so all emails are retried.

---

perma_web/perma/middleware.py

This is a followup on https://github.com/harvard-lil/perma/pull/2767
"if there is a cookie in the response, then Cloudflare does not cache the resource." https://support.cloudflare.com/hc/en-us/articles/200172516.
The former version of this middleware redundantly handled cookies on every request... so nothing (except static assets) ever got cached (observed during testing on stage).
This PR restricts cookie-handling to the login and logout routes.... which should be sufficient.

Restrict cookie-handling to login/logout routes.

---

perma_web/perma/tasks.py

Fixes https://github.com/harvard-lil/perma/issues/2775
Without the sleep in the size monitoring thread, captures were CPU-intensive enough to make my fan run; the sleep of 0.2s seems sufficient, but, if load on the workers is too high, we can make this sleep longer.

Enforce size limit in threads too.

---

perma_web/perma/settings/deployments/settings_common.py

https://github.com/harvard-lil/perma/pull/2768 improved things, but there's been at least one playback that needed more than 9 seconds. Let's see if another second does the job.

See if another second is enough for remaining timeouts.

---

perma_web/perma/wsgi.py

After getting the most recent changes in develop, `d fab run:use_ssl=True` was failing.
With some debugging I was able to find that running django with `runserver_plus` was failing while `runserver` was working OK - that led me down a google rabbit hole looking at the new celery/django settings plus django-extensions plus werkzeug and I kept seeing issues/code related to environment settings. That led me to blindly try removing this old command, which seems to be the old way of configuring celery with django.
After removing this line, using `runserver_plus` works again.

Remove conflicting os environ celery settings

---

perma_web/perma/models.py
perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/tasks.py

Some websites are evading capture... and after a couple of days investigating, it looks like it's a combination of our IP address, the headers we are sending (or not sending), and the order the headers are specified in. 
We aren't the first people to notice this sort of thing (e.g. https://sansec.io/labs/2017/05/02/http-header-order-is-important/).
After a couple days of experimenting, it looks like the headers and order in this PR are working... for now. Who knows how long that will last... but I'll plan to check on this weekly or so, and if it looks like this is insufficient or if the situation changes, I'll readdress.
Closes https://github.com/harvard-lil/perma/issues/2779

Tweak HTTP headers

---

perma_web/perma/views/user_management.py

On the admin stats page, this wraps the appending of celery queues in a try-except, since occasionally `reserved` or `stats` does not include `queue`. It is an effort to reduce noise in error reporting.

Try adding queue

---

perma_web/perma/tasks.py

https://github.com/harvard-lil/perma/pull/2780 let us start capturing a new set of pages... many of which reliably throw the below error during screenshot capture:
```
WebDriverException
Message: {"errorMessage":"null is not an object (evaluating 'a.clientWidth')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:35805","User-Agent":"Python-urllib/3.7"},"httpVersion":"1.1","method":"GET","url":"/size","urlParsed":{"anchor":"","query":"","file":"size","directory":"/","path":"/size","relative":"/size","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/size","queryKey":{},"chunks":["size"]},"urlOriginal":"/session/e9e5b500-882e-11ea …
```

Don't error out if the page appears sizeless.

---

perma_web/perma/tasks.py

I saw that a ~306MB Perma Link was created this weekend... suggesting that https://github.com/harvard-lil/perma/pull/2776 wasn't the whole story.
This PR adds limit-checking to the `while` loop that waits for all pending requests to return, which cut new local captures of that site down to about 115-130MB... still pretty significantly over the local limit, which is 100MB, but much closer.

Further limit over-large recordings

---

perma_web/static/bundles/global.css
perma_web/static/css/style-responsive.scss

A user reported a badly-behaved select list:
Turns out to be specific to Chrome (though I did not test on platforms other than Mac): `overflow: visible` totally messes up `select` elements. I do not recall this being true in the past; might be a relatively recent development.
This PR sets a standard overflow on select elements, as a workaround, and makes the input taller (which has been bugging me).

Fix select lists on Chrome

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/base-responsive.html
perma_web/perma/templates/includes/analytics.html

To enable, set `USE_ANALYTICS = True`.
The list of routes can be configured using `USE_ANALYTICS_VIEWS`. List values are the names of the views as found in https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/urls.py

Add analytics to public-facing pages (except playbacks).

---

perma_web/api/tests/test_link_resource.py
perma_web/api/views.py
perma_web/fixtures/archive.json
perma_web/perma/models.py
perma_web/perma/tests/test_models.py
perma_web/perma/views/user_management.py
perma_web/static/bundles/create.js
perma_web/static/bundles/global.css
perma_web/static/css/style-responsive.scss
perma_web/static/js/create-link.module.js
perma_web/static/js/folder-tree.module.js
perma_web/static/js/hbs/org-list-template.handlebars
perma_web/static/js/helpers/folder-selector.helper.js

- sponsored links aren't counted against a user's personal link limit
- you can't move links to the root sponsored folder
- top-level sponsored folders appear in the folder-selection dropdown, for users who get a dropdown
- slightly better handling of sponsored folders in the link batch modal's dropdown, and the dropdown you can use to move a link to a new folder

Fixes for sponsored users

---

perma_web/perma/tasks.py

As far as I can tell, everything is fine... but this task fails sometimes. Looks to be that this route is just slow to load, sometimes. Which, maybe means it's not the best for monitoring, since that suggests it's expensive.... but while I think about an alternative, this might quiet all those spurious error emails from stage.

Double timeout; 5s too short for stage.

---

docker-compose.yml

https://chromereleases.googleblog.com/2020/06/stable-channel-update-for-desktop_22.html

Bump image version to get new Chrome installed at Circle

---

docker-compose.yml

As of this writing, this replaces Chrome 83.0.4103.116 with 84.0.4147.89 -- see https://chromereleases.googleblog.com/2020/07/stable-channel-update-for-desktop.html and https://chromium.googlesource.com/chromium/src/+log/83.0.4103.116..84.0.4147.89?pretty=fuller&n=10000

Bump image version to get new Chrome

---

docker-compose.yml

This upgrades Chrome from 84.0.4147.89 to 84.0.4147.105 at Circle CI. To get this upgrade locally, I had to run 
```
docker-compose down
docker system prune --all
docker-compose up -d
```
which seems heavy-handed; I did not find the `--no-cache` option mentioned in https://github.com/harvard-lil/perma/pull/2822#issuecomment-664456351

Bump image version to get new Chrome at Circle CI

---

perma_web/perma/settings/deployments/settings_common.py
perma_web/perma/templates/archive/iframe.html

You have to click on the screenshot to see it at normal size; the alt text is the same as the src... but, present!

Client-side playback: add screenshot, update

---

perma_web/perma/models.py

We think this only happens if a valid target URL redirect to an invalid location.

Catch InvalidURL if thrown by requests.
